/*
 * Copyright (c) 2018 zhtlab
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit
 * persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef _STM32L0RCC_H_
#define _STM32L0RCC_H_

/* STM32L0x2 reference manual  DocID025941 Rev 5 */

#define RCC_CLOCK_HPRETABLE     {0, 0, 0, 0,  0, 0, 0, 0,  1, 2, 3, 4,  6, 7, 8, 9}
#define RCC_CLOCK_PPRETABLE     {0, 0, 0, 0,  1, 2, 3, 4}

typedef struct {
  __IO uint32_t         CR;             /* 0x00 */
#define RCC_CR_PLLRDY_SHIFT             25
#define RCC_CR_PLLRDY_MASK              (1 << (RCC_CR_PLLRDY_SHIFT))
#define RCC_CR_PLLON_SHIFT              24
#define RCC_CR_PLLON_MASK               (1 << (RCC_CR_PLLON_SHIFT))
#define RCC_CR_PLLON_NO                 (0 << (RCC_CR_PLLON_SHIFT))
#define RCC_CR_PLLON_YES                (1 << (RCC_CR_PLLON_SHIFT))
#define RCC_CR_RTCPRE_SHIFT             20
#define RCC_CR_RTCPRE_MASK              (3 << (RCC_CR_RTCPRE_SHIFT))
#define RCC_CR_RTCPRE_DIV2              (0 << (RCC_CR_RTCPRE_SHIFT))
#define RCC_CR_RTCPRE_DIV4              (1 << (RCC_CR_RTCPRE_SHIFT))
#define RCC_CR_RTCPRE_DIV8              (2 << (RCC_CR_RTCPRE_SHIFT))
#define RCC_CR_RTCPRE_DIV16             (3 << (RCC_CR_RTCPRE_SHIFT))
#define RCC_CR_CSSHSEON_SHIFT           19
#define RCC_CR_CSSHSEON_MASK            (1 << (RCC_CR_CSSHSEON_SHIFT))
#define RCC_CR_CSSHSEON_NO              (0 << (RCC_CR_CSSHSEON_SHIFT))
#define RCC_CR_CSSHSEON_YES             (1 << (RCC_CR_CSSHSEON_SHIFT))
#define RCC_CR_HSEBYP_SHIFT             18
#define RCC_CR_HSEBYP_MASK              (1 << (RCC_CR_HSEBYP_SHIFT))
#define RCC_CR_HSEBYP_NO                (0 << (RCC_CR_HSEBYP_SHIFT))
#define RCC_CR_HSEBYP_YES               (1 << (RCC_CR_HSEBYP_SHIFT))
#define RCC_CR_HSERDY_SHIFT             17
#define RCC_CR_HSERDY_MASK              (1 << (RCC_CR_HSERDY_SHIFT))
#define RCC_CR_HSEON_SHIFT              16
#define RCC_CR_HSEON_MASK               (1 << (RCC_CR_HSEON_SHIFT))
#define RCC_CR_HSEON_NO                 (0 << (RCC_CR_HSEON_SHIFT))
#define RCC_CR_HSEON_YES                (1 << (RCC_CR_HSEON_SHIFT))
#define RCC_CR_MSIRDY_SHIFT             9
#define RCC_CR_MSIRDY_MASK              (1 << (RCC_CR_MSIRDY_SHIFT))
#define RCC_CR_MSION_SHIFT              8
#define RCC_CR_MSION_MASK               (1 << (RCC_CR_MSION_SHIFT))
#define RCC_CR_MSION_NO                 (0 << (RCC_CR_MSION_SHIFT))
#define RCC_CR_MSION_YES                (1 << (RCC_CR_MSION_SHIFT))
#define RCC_CR_HSI16OUTEN_SHIFT         5
#define RCC_CR_HSI16OUTEN_MASK          (1 << (RCC_CR_HSI16OUTEN_SHIFT))
#define RCC_CR_HSI16OUTEN_NO            (0 << (RCC_CR_HSI16OUTEN_SHIFT))
#define RCC_CR_HSI16OUTEN_YES           (1 << (RCC_CR_HSI16OUTEN_SHIFT))
#define RCC_CR_HSI16DIVF_SHIFT          4
#define RCC_CR_HSI16DIVF_MASK           (1 << (RCC_CR_HSI16DIVF_SHIFT))
#define RCC_CR_HSI16DIVEN_SHIFT         3
#define RCC_CR_HSI16DIVEN_MASK          (1 << (RCC_CR_HSI16DIVEN_SHIFT))
#define RCC_CR_HSI16DIVEN_NO            (0 << (RCC_CR_HSI16DIVEN_SHIFT))
#define RCC_CR_HSI16DIVEN_YES           (1 << (RCC_CR_HSI16DIVEN_SHIFT))
#define RCC_CR_HSI16RDYF_SHIFT          2
#define RCC_CR_HSI16RDYF_MASK           (1 << (RCC_CR_HSI16RDYF_SHIFT))
#define RCC_CR_HSI16ERON_SHIFT          1
#define RCC_CR_HSI16ERON_MASK           (1 << (RCC_CR_HSI16ERON_SHIFT))
#define RCC_CR_HSI16ERON_NO             (0 << (RCC_CR_HSI16ERON_SHIFT))
#define RCC_CR_HSI16ERON_YES            (1 << (RCC_CR_HSI16ERON_SHIFT))
#define RCC_CR_HSI16ON_SHIFT            0
#define RCC_CR_HSI16ON_MASK             (1 << (RCC_CR_HSI16ON_SHIFT))
#define RCC_CR_HSI16ON_NO               (0 << (RCC_CR_HSI16ON_SHIFT))
#define RCC_CR_HSI16ON_YES              (1 << (RCC_CR_HSI16ON_SHIFT))

#define RCC_CR_HSIRDY_MASK              (RCC_CR_HSI16RDYF_MASK)
#define RCC_CR_HSION_YES                (RCC_CR_HSI16ON_YES)

  __IO uint32_t         ICSCR;          /* 0x04 */
#define RCC_ICSCR_MSITRIM_SHIFT         24
#define RCC_ICSCR_MSITRIM_MASK          (0x1f << (RCC_ICSCR_HSITRIM_SHIFT))
#define RCC_ICSCR_MSICAL_SHIFT          16
#define RCC_ICSCR_MSICAL_MASK           (0xff << (RCC_ICSCR_HSICAL_SHIFT))
#define RCC_ICSCR_MSIRANGE_SHIFT        13
#define RCC_ICSCR_MSIRANGE_MASK         (0x7 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_MSIRANGE_65536HZ      (0 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_MSIRANGE_131072HZ     (1 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_MSIRANGE_262144HZ     (2 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_MSIRANGE_524288HZ     (3 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_MSIRANGE_1048KHZ      (4 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_MSIRANGE_2097KHZ      (5 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_MSIRANGE_4194KHZ      (6 << (RCC_ICSCR_MSIRANGE_SHIFT))
#define RCC_ICSCR_HSI16TRIM_SHIFT       8
#define RCC_ICSCR_HSI16TRIM_MASK        (0x1f << (RCC_ICSCR_HSI16TRIM_SHIFT))
#define RCC_ICSCR_HSI16CAL_SHIFT        0
#define RCC_ICSCR_HSI16CAL_MASK         (0xff << (RCC_ICSCR_HSI16CAL_SHIFT))

  __IO uint32_t         CRRCR;          /* 0x08 */
#define RCC_CRRCR_HSI48CAL_SHIFT        8
#define RCC_CRRCR_HSI48CAL_MASK         (0xff << (RCC_CRRCR_HSI48CAL_SHIFT))
#define RCC_CRRCR_HSI48DIV6EN_SHIFT     2
#define RCC_CRRCR_HSI48DIV6EN_MASK      (1 << (RCC_CRRCR_HSI48DIV6EN_SHIFT))
#define RCC_CRRCR_HSI48DIV6EN_NO        (0 << (RCC_CRRCR_HSI48DIV6EN_SHIFT))
#define RCC_CRRCR_HSI48DIV6EN_YES       (1 << (RCC_CRRCR_HSI48DIV6EN_SHIFT))
#define RCC_CRRCR_HSI48RDY_SHIFT        1
#define RCC_CRRCR_HSI48RDY_MASK         (1 << (RCC_CRRCR_HSI48RDY_SHIFT))
#define RCC_CRRCR_HSI48RDY_NO           (0 << (RCC_CRRCR_HSI48RDY_SHIFT))
#define RCC_CRRCR_HSI48RDY_YES          (1 << (RCC_CRRCR_HSI48RDY_SHIFT))
#define RCC_CRRCR_HSI48ON_SHIFT         0
#define RCC_CRRCR_HSI48ON_MASK          (1 << (RCC_CRRCR_HSI48ON_SHIFT))
#define RCC_CRRCR_HSI48ON_NO            (0 << (RCC_CRRCR_HSI48ON_SHIFT))
#define RCC_CRRCR_HSI48ON_YES           (1 << (RCC_CRRCR_HSI48ON_SHIFT))


  __IO uint32_t         CFGR;           /* 0x0c */
#define RCC_CFGR_MCOPRE_SHIFT           28
#define RCC_CFGR_MCOPRE_MASK            (7 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV1            (0 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV2            (1 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV4            (2 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV7            (3 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV16           (4 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOSEL_SHIFT           24
#define RCC_CFGR_MCOSEL_MASK            (0xf << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_DISABLE         (0 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_SYSCLK          (1 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_HSI16           (2 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_MSI             (3 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_HSE             (4 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_MAINPLL         (5 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_LSI             (6 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_HSI48           (8 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_PLLDIV_SHIFT           22
#define RCC_CFGR_PLLDIV_MASK            (3 << (RCC_CFGR_PLLDIV_SHIFT))
#define RCC_CFGR_PLLDIV_DIV(x)          (((x)-1) << (RCC_CFGR_PLLDIV_SHIFT))
#define RCC_CFGR_PLLDIV_RESERVED0       (0 << (RCC_CFGR_PLLDIV_SHIFT))
#define RCC_CFGR_PLLDIV_INVALID0        (0 << (RCC_CFGR_PLLDIV_SHIFT))
#define RCC_CFGR_PLLDIV_DIV2            (1 << (RCC_CFGR_PLLDIV_SHIFT))
#define RCC_CFGR_PLLDIV_DIV3            (2 << (RCC_CFGR_PLLDIV_SHIFT))
#define RCC_CFGR_PLLDIV_DIV4            (3 << (RCC_CFGR_PLLDIV_SHIFT))
#define RCC_CFGR_PLLMUL_SHIFT           18
#define RCC_CFGR_PLLMUL_MASK            (0xf << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X3              (0 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X4              (1 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X6              (2 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X8              (3 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X12             (4 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X16             (5 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X24             (6 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X32             (7 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLMUL_X48             (8 << (RCC_CFGR_PLLMUL_SHIFT))
#define RCC_CFGR_PLLSRC_SHIFT           16
#define RCC_CFGR_PLLSRC_MASK            (1 << (RCC_CFGR_PLLSRC_SHIFT))
#define RCC_CFGR_PLLSRC_HSI16           (0 << (RCC_CFGR_PLLSRC_SHIFT))
#define RCC_CFGR_PLLSRC_HSE             (1 << (RCC_CFGR_PLLSRC_SHIFT))
#define RCC_CFGR_STOPWUCK_SHIFT         15
#define RCC_CFGR_STOPWUCK_MASK          (1 << (RCC_CFGR_STOPWUCK_SHIFT))
#define RCC_CFGR_STOPWUCK_NO            (0 << (RCC_CFGR_STOPWUCK_SHIFT))
#define RCC_CFGR_STOPWUCK_YES           (1 << (RCC_CFGR_STOPWUCK_SHIFT))
#define RCC_CFGR_PPRE2_SHIFT		11		/* APB2 */
#define RCC_CFGR_PPRE2_MASK		(7 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV1		(0 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV2		(4 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV4		(5 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV8		(6 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV16		(7 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE1_SHIFT		8		/* APB1 */
#define RCC_CFGR_PPRE1_MASK		(7 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV1		(0 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV2		(4 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV4		(5 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV8		(6 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV16		(7 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_HPRE_SHIFT             4               /* AHB */
#define RCC_CFGR_HPRE_MASK		(0xf << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV1		(0 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV2		(8 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV4		(9 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV8		(10 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV16             (11 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV64             (12 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV128            (13 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV256            (14 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV512            (15 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_SWS_SHIFT              2
#define RCC_CFGR_SWS_MASK               (3 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_MSI                (0 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_HSI16              (1 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_HSE                (2 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_PLL                (3 << (RCC_CFGR_SWS_SHIFT))
#define         RCC_CFGR_SWS_HSI        (RCC_CFGR_SWS_HSI16)
#define RCC_CFGR_SW_SHIFT               0
#define RCC_CFGR_SW_MASK                (3 << (RCC_CFGR_SW_SHIFT))
#define RCC_CFGR_SW_MSI                 (0 << (RCC_CFGR_SW_SHIFT))
#define RCC_CFGR_SW_HSI16               (1 << (RCC_CFGR_SW_SHIFT))
#define         RCC_CFGR_SW_HSI         (RCC_CFGR_SW_HSI16)
#define RCC_CFGR_SW_HSE                 (2 << (RCC_CFGR_SW_SHIFT))
#define RCC_CFGR_SW_PLL                 (3 << (RCC_CFGR_SW_SHIFT))

  __IO uint32_t         CIER;           /* 0x10 */
#define RCC_CIER_CSSLSEIE_SHIFT         7
#define RCC_CIER_CSSLSEIE_MASK		(1 << (RCC_CIER_CSSLSEIE_SHIFT))
#define RCC_CIER_CSSLSEIE_NO		(0 << (RCC_CIER_CSSLSEIE_SHIFT))
#define RCC_CIER_CSSLSEIE_YES		(1 << (RCC_CIER_CSSLSEIE_SHIFT))
#define RCC_CIER_HSI48_RDYIE_SHIFT      6
#define RCC_CIER_HSI48_RDYIE_MASK	(1 << (RCC_CIER_HSI48_RDYIE_SHIFT))
#define RCC_CIER_HSI48_RDYIE_NO		(0 << (RCC_CIER_HSI48_RDYIE_SHIFT))
#define RCC_CIER_HSI48_RDYIE_YES	(1 << (RCC_CIER_HSI48_RDYIE_SHIFT))
#define RCC_CIER_MSI_RDYIE_SHIFT	5
#define RCC_CIER_MSI_RDYIE_MASK		(1 << (RCC_CIER_MSI_RDYIE_SHIFT))
#define RCC_CIER_MSI_RDYIE_NO		(0 << (RCC_CIER_MSI_RDYIE_SHIFT))
#define RCC_CIER_MSI_RDYIE_YES		(1 << (RCC_CIER_MSI_RDYIE_SHIFT))
#define RCC_CIER_PLL_RDYIE_SHIFT	4
#define RCC_CIER_PLL_RDYIE_MASK		(1 << (RCC_CIER_PLL_RDYIE_SHIFT))
#define RCC_CIER_PLL_RDYIE_NO		(0 << (RCC_CIER_PLL_RDYIE_SHIFT))
#define RCC_CIER_PLL_RDYIE_YES		(1 << (RCC_CIER_PLL_RDYIE_SHIFT))
#define RCC_CIER_HSE_RDYIE_SHIFT        3
#define RCC_CIER_HSE_RDYIE_MASK         (1 << (RCC_CIER_HSE_RDYIE_SHIFT))
#define RCC_CIER_HSE_RDYIE_NO           (0 << (RCC_CIER_HSE_RDYIE_SHIFT))
#define RCC_CIER_HSE_RDYIE_YES          (1 << (RCC_CIER_HSE_RDYIE_SHIFT))
#define RCC_CIER_HSI16_RDYIE_SHIFT      2
#define RCC_CIER_HSI16_RDYIE_MASK       (1 << (RCC_CIER_HSI16_RDYIE_SHIFT))
#define RCC_CIER_HSI16_RDYIE_NO         (0 << (RCC_CIER_HSI16_RDYIE_SHIFT))
#define RCC_CIER_HSI16_RDYIE_YES        (1 << (RCC_CIER_HSI16_RDYIE_SHIFT))
#define RCC_CIER_LSE_RDYIE_SHIFT	1
#define RCC_CIER_LSE_RDYIE_MASK		(1 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSE_RDYIE_NO		(0 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSE_RDYIE_YES		(1 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSI_RDYIE_SHIFT	0
#define RCC_CIER_LSI_RDYIE_MASK		(1 << (RCC_CIER_LSI_RDYIE_SHIFT))
#define RCC_CIER_LSI_RDYIE_NO		(0 << (RCC_CIER_LSI_RDYIE_SHIFT))
#define RCC_CIER_LSI_RDYIE_YES		(1 << (RCC_CIER_LSI_RDYIE_SHIFT))

  __IO uint32_t         CIFR;           /* 0x14 */
#define RCC_CIFR_CSSHSEF_SHIFT          8
#define RCC_CIFR_CSSHSEF_MASK           (1 << (RCC_CIFR_CSSHSEF_SHIFT))
#define RCC_CIFR_CSSLSEF_SHIFT          7
#define RCC_CIFR_CSSLSEF_MASK           (1 << (RCC_CIFR_CSSLSEF_SHIFT))
#define RCC_CIFR_HSI48_RDYF_SHIFT       6
#define RCC_CIFR_HSI48_RDYF_MASK        (1 << (RCC_CIFR_HSI48_RDYF_SHIFT))
#define RCC_CIFR_MSI_RDYF_SHIFT         5
#define RCC_CIFR_MSI_RDYF_MASK          (1 << (RCC_CIFR_MSI_RDYF_SHIFT))
#define RCC_CIFR_PLL_RDYF_SHIFT         4
#define RCC_CIFR_PLL_RDYF_MASK          (1 << (RCC_CIFR_PLL_RDYF_SHIFT))
#define RCC_CIFR_HSE_RDYF_SHIFT         3
#define RCC_CIFR_HSE_RDYF_MASK          (1 << (RCC_CIFR_HSE_RDYF_SHIFT))
#define RCC_CIFR_HSI_RDYF_SHIFT         2
#define RCC_CIFR_HSI_RDYF_MASK          (1 << (RCC_CIFR_HSI_RDYF_SHIFT))
#define RCC_CIFR_LSE_RDYF_SHIFT         1
#define RCC_CIFR_LSE_RDYF_MASK          (1 << (RCC_CIFR_LSE_RDYF_SHIFT))
#define RCC_CIFR_LSI_RDYF_SHIFT         0
#define RCC_CIFR_LSI_RDYF_MASK          (1 << (RCC_CIFR_LSI_RDYF_SHIFT))

  __IO uint32_t         CICR;           /* 0x18 */
#define RCC_CICR_CSSHSEC_SHIFT          8
#define RCC_CICR_CSSHSEC_MASK           (1 << (RCC_CICR_CSSHSEC_SHIFT))
#define RCC_CICR_CSSLSEC_SHIFT          7
#define RCC_CICR_CSSLSEC_MASK           (1 << (RCC_CICR_CSSLSEC_SHIFT))
#define RCC_CICR_HSI48_RDYC_SHIFT       6
#define RCC_CICR_HSI48_RDYC_MASK        (1 << (RCC_CICR_HSI48_RDYC_SHIFT))
#define RCC_CICR_MSI_RDYC_SHIFT         5
#define RCC_CICR_MSI_RDYC_MASK          (1 << (RCC_CICR_MSI_RDYC_SHIFT))
#define RCC_CICR_PLL_RDYC_SHIFT         4
#define RCC_CICR_PLL_RDYC_MASK          (1 << (RCC_CICR_PLL_RDYC_SHIFT))
#define RCC_CICR_HSE_RDYC_SHIFT         3
#define RCC_CICR_HSE_RDYC_MASK          (1 << (RCC_CICR_HSE_RDYC_SHIFT))
#define RCC_CICR_HSI_RDYC_SHIFT         2
#define RCC_CICR_HSI_RDYC_MASK          (1 << (RCC_CICR_HSI_RDYC_SHIFT))
#define RCC_CICR_LSE_RDYC_SHIFT         1
#define RCC_CICR_LSE_RDYC_MASK          (1 << (RCC_CICR_LSE_RDYC_SHIFT))
#define RCC_CICR_LSI_RDYC_SHIFT         0
#define RCC_CICR_LSI_RDYC_MASK          (1 << (RCC_CICR_LSI_RDYC_SHIFT))

  __IO uint32_t         IOPRSTR;        /* 0x1c */

  __IO uint32_t         AHBRSTR;        /* 0x20 */
#define RCC_AHBRSTR_MIFRST_SHIFT        8
#define RCC_AHBRSTR_MIFRST_MASK         (1 << (RCC_AHBRSTR_MIFRST_SHIFT))
#define RCC_AHBRSTR_MIFRST_NO           (0 << (RCC_AHBRSTR_MIFRST_SHIFT))
#define RCC_AHBRSTR_MIFRST_YES          (1 << (RCC_AHBRSTR_MIFRST_SHIFT))
#define RCC_AHBRSTR_DMARST_SHIFT        0
#define RCC_AHBRSTR_DMARST_MASK         (1 << (RCC_AHBRSTR_DMARST_SHIFT))
#define RCC_AHBRSTR_DMARST_NO           (0 << (RCC_AHBRSTR_DMARST_SHIFT))
#define RCC_AHBRSTR_DMARST_YES          (1 << (RCC_AHBRSTR_DMARST_SHIFT))

  __IO uint32_t         APB2RSTR;       /* 0x24 */
#define RCC_APB2RSTR_USART1RSTR_SHIFT   14
#define RCC_APB2RSTR_USART1RSTR_MASK    (1 << (RCC_APB2RSTR_USART1RSTR_SHIFT))
#define RCC_APB2RSTR_USART1RSTR_NO      (0 << (RCC_APB2RSTR_USART1RSTR_SHIFT))
#define RCC_APB2RSTR_USART1RSTR_YES     (1 << (RCC_APB2RSTR_USART1RSTR_SHIFT))
#define RCC_APB2RSTR_SPI1RSTR_SHIFT     12
#define RCC_APB2RSTR_SPI1RSTR_MASK      (1 << (RCC_APB2RSTR_SPI1RSTR_SHIFT))
#define RCC_APB2RSTR_SPI1RSTR_NO        (0 << (RCC_APB2RSTR_SPI1RSTR_SHIFT))
#define RCC_APB2RSTR_SPI1RSTR_YES       (1 << (RCC_APB2RSTR_SPI1RSTR_SHIFT))
#define RCC_APB2RSTR_TIM22RSTR_SHIFT    5
#define RCC_APB2RSTR_TIM22RSTR_MASK     (1 << (RCC_APB2RSTR_TIM22RSTR_SHIFT))
#define RCC_APB2RSTR_TIM22RSTR_NO       (0 << (RCC_APB2RSTR_TIM22RSTR_SHIFT))
#define RCC_APB2RSTR_TIM22RSTR_YES      (1 << (RCC_APB2RSTR_TIM22RSTR_SHIFT))
#define RCC_APB2RSTR_TIM21RSTR_SHIFT    2
#define RCC_APB2RSTR_TIM21RSTR_MASK     (1 << (RCC_APB2RSTR_TIM21RSTR_SHIFT))
#define RCC_APB2RSTR_TIM21RSTR_NO       (0 << (RCC_APB2RSTR_TIM21RSTR_SHIFT))
#define RCC_APB2RSTR_TIM21RSTR_YES      (1 << (RCC_APB2RSTR_TIM21RSTR_SHIFT))
#define RCC_APB2RSTR_SYSCFGRSTR_SHIFT   0
#define RCC_APB2RSTR_SYSCFGRSTR_MASK    (1 << (RCC_APB2RSTR_SYSCFGRSTR_SHIFT))
#define RCC_APB2RSTR_SYSCFGRSTR_NO      (0 << (RCC_APB2RSTR_SYSCFGRSTR_SHIFT))
#define RCC_APB2RSTR_SYSCFGRSTR_YES     (1 << (RCC_APB2RSTR_SYSCFGRSTR_SHIFT))

  __IO uint32_t         APB1RSTR;       /* 0x28 */
#define RCC_APB1RSTR_CRSRST_SHIFT       27
#define RCC_APB1RSTR_CRSRST_MASK        (1 << (RCC_APB1RSTR_CRSRST_SHIFT))
#define RCC_APB1RSTR_CRSRST_NO          (0 << (RCC_APB1RSTR_CRSRST_SHIFT))
#define RCC_APB1RSTR_CRSRST_YES         (1 << (RCC_APB1RSTR_CRSRST_SHIFT))

  __IO uint32_t         IOPENR;         /* 0x2c */
#define RCC_IOPENR_IOPHEN_SHIFT         7
#define RCC_IOPENR_IOPHEN_MASK          (1 << (RCC_IOPENR_IOPHEN_SHIFT))
#define RCC_IOPENR_IOPHEN_NO            (0 << (RCC_IOPENR_IOPHEN_SHIFT))
#define RCC_IOPENR_IOPHEN_YES           (1 << (RCC_IOPENR_IOPHEN_SHIFT))
#define RCC_IOPENR_IOPEEN_SHIFT         4
#define RCC_IOPENR_IOPEEN_MASK          (1 << (RCC_IOPENR_IOPEEN_SHIFT))
#define RCC_IOPENR_IOPEEN_NO            (0 << (RCC_IOPENR_IOPEEN_SHIFT))
#define RCC_IOPENR_IOPEEN_YES           (1 << (RCC_IOPENR_IOPEEN_SHIFT))
#define RCC_IOPENR_IOPDEN_SHIFT         3
#define RCC_IOPENR_IOPDEN_MASK          (1 << (RCC_IOPENR_IOPDEN_SHIFT))
#define RCC_IOPENR_IOPDEN_NO            (0 << (RCC_IOPENR_IOPDEN_SHIFT))
#define RCC_IOPENR_IOPDEN_YES           (1 << (RCC_IOPENR_IOPDEN_SHIFT))
#define RCC_IOPENR_IOPCEN_SHIFT         2
#define RCC_IOPENR_IOPCEN_MASK          (1 << (RCC_IOPENR_IOPCEN_SHIFT))
#define RCC_IOPENR_IOPCEN_NO            (0 << (RCC_IOPENR_IOPCEN_SHIFT))
#define RCC_IOPENR_IOPCEN_YES           (1 << (RCC_IOPENR_IOPCEN_SHIFT))
#define RCC_IOPENR_IOPBEN_SHIFT         1
#define RCC_IOPENR_IOPBEN_MASK          (1 << (RCC_IOPENR_IOPBEN_SHIFT))
#define RCC_IOPENR_IOPBEN_NO            (0 << (RCC_IOPENR_IOPBEN_SHIFT))
#define RCC_IOPENR_IOPBEN_YES           (1 << (RCC_IOPENR_IOPBEN_SHIFT))
#define RCC_IOPENR_IOPAEN_SHIFT         0
#define RCC_IOPENR_IOPAEN_MASK          (1 << (RCC_IOPENR_IOPAEN_SHIFT))
#define RCC_IOPENR_IOPAEN_NO            (0 << (RCC_IOPENR_IOPAEN_SHIFT))
#define RCC_IOPENR_IOPAEN_YES           (1 << (RCC_IOPENR_IOPAEN_SHIFT))

#define RCC_GPIOAEN_YES                 (RCC_IOPENR_IOPAEN_YES)
#define RCC_GPIOBEN_YES                 (RCC_IOPENR_IOPBEN_YES)
#define RCC_GPIOCEN_YES                 (RCC_IOPENR_IOPCEN_YES)
#define RCC_GPIODEN_YES                 (RCC_IOPENR_IOPDEN_YES)
#define RCC_GPIOEEN_YES                 (RCC_IOPENR_IOPEEN_YES)
#define RCC_GPIOHEN_YES                 (RCC_IOPENR_IOPHEN_YES)

  __IO uint32_t         AHB1ENR;        /* 0x30 */
#define RCC_AHB1ENR_TSCEN_SHIFT		16
#define RCC_AHB1ENR_TSCEN_MASK		(1 << (RCC_AHB1ENR_TSCEN_SHIFT))
#define RCC_AHB1ENR_TSCEN_NO		(0 << (RCC_AHB1ENR_TSCEN_SHIFT))
#define RCC_AHB1ENR_TSCEN_YES		(1 << (RCC_AHB1ENR_TSCEN_SHIFT))
#define RCC_AHB1ENR_CRCEN_SHIFT		12
#define RCC_AHB1ENR_CRCEN_MASK		(1 << (RCC_AHB1ENR_CRCEN_SHIFT))
#define RCC_AHB1ENR_CRCEN_NO		(0 << (RCC_AHB1ENR_CRCEN_SHIFT))
#define RCC_AHB1ENR_CRCEN_YES		(1 << (RCC_AHB1ENR_CRCEN_SHIFT))
#define RCC_AHB1ENR_MIFEN_SHIFT         8
#define RCC_AHB1ENR_MIFEN_MASK          (1 << (RCC_AHB1ENR_MIFEN_SHIFT))
#define RCC_AHB1ENR_MIFEN_NO            (0 << (RCC_AHB1ENR_MIFEN_SHIFT))
#define RCC_AHB1ENR_MIFEN_YES           (1 << (RCC_AHB1ENR_MIFEN_SHIFT))
#define RCC_AHB1ENR_FLASHEN_SHIFT       (RCC_AHB1ENR_MIFEN_SHIFT)
#define RCC_AHB1ENR_FLASHEN_MASK        (RCC_AHB1ENR_MIFEN_MASK)
#define RCC_AHB1ENR_FLASHEN_NO          (RCC_AHB1ENR_MIFEN_NO)
#define RCC_AHB1ENR_FLASHEN_YES         (RCC_AHB1ENR_MIFEN_YES)
#define RCC_AHB1ENR_DMA1EN_SHIFT        0
#define RCC_AHB1ENR_DMA1EN_MASK         (1 << (RCC_AHB1ENR_DMA1EN_SHIFT))
#define RCC_AHB1ENR_DMA1EN_NO           (0 << (RCC_AHB1ENR_DMA1EN_SHIFT))
#define RCC_AHB1ENR_DMA1EN_YES          (1 << (RCC_AHB1ENR_DMA1EN_SHIFT))

  __IO uint32_t         APB2ENR;        /* 0x34 */
#define RCC_APB2ENR_USART1EN_SHIFT	14
#define RCC_APB2ENR_USART1EN_MASK	(1 << (RCC_APB2ENR_USART1EN_SHIFT))
#define RCC_APB2ENR_USART1EN_NO		(0 << (RCC_APB2ENR_USART1EN_SHIFT))
#define RCC_APB2ENR_USART1EN_YES	(1 << (RCC_APB2ENR_USART1EN_SHIFT))
#define RCC_APB2ENR_SPI1EN_SHIFT	12
#define RCC_APB2ENR_SPI1EN_MASK		(1 << (RCC_APB2ENR_SPI1EN_SHIFT))
#define RCC_APB2ENR_SPI1EN_NO		(0 << (RCC_APB2ENR_SPI1EN_SHIFT))
#define RCC_APB2ENR_SPI1EN_YES		(1 << (RCC_APB2ENR_SPI1EN_SHIFT))
#define RCC_APB2ENR_FWEN_SHIFT		7
#define RCC_APB2ENR_FWEN_MASK		(1 << (RCC_APB2ENR_FWEN_SHIFT))
#define RCC_APB2ENR_FWEN_NO		(0 << (RCC_APB2ENR_FWEN_SHIFT))
#define RCC_APB2ENR_FWEN_YES		(1 << (RCC_APB2ENR_FWEN_SHIFT))
#define RCC_APB2ENR_TIM22EN_SHIFT	5
#define RCC_APB2ENR_TIM22EN_MASK	(1 << (RCC_APB2ENR_TIM22EN_SHIFT))
#define RCC_APB2ENR_TIM22EN_NO		(0 << (RCC_APB2ENR_TIM22EN_SHIFT))
#define RCC_APB2ENR_TIM22EN_YES		(1 << (RCC_APB2ENR_TIM22EN_SHIFT))
#define RCC_APB2ENR_TIM21EN_SHIFT	2
#define RCC_APB2ENR_TIM21EN_MASK	(1 << (RCC_APB2ENR_TIM21EN_SHIFT))
#define RCC_APB2ENR_TIM21EN_NO		(0 << (RCC_APB2ENR_TIM21EN_SHIFT))
#define RCC_APB2ENR_TIM21EN_YES		(1 << (RCC_APB2ENR_TIM21EN_SHIFT))
#define RCC_APB2ENR_SYSCFGEN_SHIFT	0
#define RCC_APB2ENR_SYSCFGEN_MASK	(1 << (RCC_APB2ENR_SYSCFGEN_SHIFT))
#define RCC_APB2ENR_SYSCFGEN_NO		(0 << (RCC_APB2ENR_SYSCFGEN_SHIFT))
#define RCC_APB2ENR_SYSCFGEN_YES	(1 << (RCC_APB2ENR_SYSCFGEN_SHIFT))

  __IO uint32_t         APB1ENR;       /* 0x38 */
#define RCC_APB1ENR_LPTIM1EN_SHIFT      31
#define RCC_APB1ENR_LPTIM1EN_MASK       (1 << (RCC_APB1ENR_LPTIM1EN_SHIFT))
#define RCC_APB1ENR_LPTIM1EN_NO         (0 << (RCC_APB1ENR_LPTIM1EN_SHIFT))
#define RCC_APB1ENR_LPTIM1EN_YES        (1 << (RCC_APB1ENR_LPTIM1EN_SHIFT))
#define RCC_APB1ENR_I2C3EN_SHIFT        30
#define RCC_APB1ENR_I2C3EN_MASK         (1 << (RCC_APB1ENR_I2C3EN_SHIFT))
#define RCC_APB1ENR_I2C3EN_NO		(0 << (RCC_APB1ENR_I2C3EN_SHIFT))
#define RCC_APB1ENR_I2C3EN_YES		(1 << (RCC_APB1ENR_I2C3EN_SHIFT))
#define RCC_APB1ENR_DAC1EN_SHIFT	29
#define RCC_APB1ENR_DAC1EN_MASK         (1 << (RCC_APB1ENR_DAC1EN_SHIFT))
#define RCC_APB1ENR_DAC1EN_NO		(0 << (RCC_APB1ENR_DAC1EN_SHIFT))
#define RCC_APB1ENR_DAC1EN_YES 		(1 << (RCC_APB1ENR_DAC1EN_SHIFT))
#define RCC_APB1ENR_PWREN_SHIFT         28
#define RCC_APB1ENR_PWREN_MASK          (1 << (RCC_APB1ENR_PWREN_SHIFT))
#define RCC_APB1ENR_PWREN_NO            (0 << (RCC_APB1ENR_PWREN_SHIFT))
#define RCC_APB1ENR_PWREN_YES           (1 << (RCC_APB1ENR_PWREN_SHIFT))
#define RCC_APB1ENR_CRSEN_SHIFT         27
#define RCC_APB1ENR_CRSEN_MASK          (1 << (RCC_APB1ENR_CRSEN_SHIFT))
#define RCC_APB1ENR_CRSEN_NO            (0 << (RCC_APB1ENR_CRSEN_SHIFT))
#define RCC_APB1ENR_CRSEN_YES           (1 << (RCC_APB1ENR_CRSEN_SHIFT))
#define RCC_APB1ENR_USBEN_SHIFT         23
#define RCC_APB1ENR_USBEN_MASK          (1 << (RCC_APB1ENR_USBEN_SHIFT))
#define RCC_APB1ENR_USBEN_NO            (0 << (RCC_APB1ENR_USBEN_SHIFT))
#define RCC_APB1ENR_USBEN_YES           (1 << (RCC_APB1ENR_USBEN_SHIFT))
#define       RCC_APB1ENR_USBFSEN_NO      (RCC_APB1ENR_USBEN_NO)
#define       RCC_APB1ENR_USBFSEN_YES     (RCC_APB1ENR_USBEN_YES)
#define RCC_APB1ENR_I2C2EN_SHIFT	22
#define RCC_APB1ENR_I2C2EN_MASK         (1 << (RCC_APB1ENR_I2C2EN_SHIFT))
#define RCC_APB1ENR_I2C2EN_NO		(0 << (RCC_APB1ENR_I2C2EN_SHIFT))
#define RCC_APB1ENR_I2C2EN_YES		(1 << (RCC_APB1ENR_I2C2EN_SHIFT))
#define RCC_APB1ENR_I2C1EN_SHIFT	21
#define RCC_APB1ENR_I2C1EN_MASK         (1 << (RCC_APB1ENR_I2C1EN_SHIFT))
#define RCC_APB1ENR_I2C1EN_NO		(0 << (RCC_APB1ENR_I2C1EN_SHIFT))
#define RCC_APB1ENR_I2C1EN_YES		(1 << (RCC_APB1ENR_I2C1EN_SHIFT))
#define RCC_APB1ENR_USART5EN_SHIFT	20
#define RCC_APB1ENR_USART5EN_MASK	(1 << (RCC_APB1ENR_USART5EN_SHIFT))
#define RCC_APB1ENR_USART5EN_NO         (0 << (RCC_APB1ENR_USART5EN_SHIFT))
#define RCC_APB1ENR_USART5EN_YES	(1 << (RCC_APB1ENR_USART5EN_SHIFT))
#define RCC_APB1ENR_USART4EN_SHIFT	19
#define RCC_APB1ENR_USART4EN_MASK	(1 << (RCC_APB1ENR_USART4EN_SHIFT))
#define RCC_APB1ENR_USART4EN_NO         (0 << (RCC_APB1ENR_USART4EN_SHIFT))
#define RCC_APB1ENR_USART4EN_YES	(1 << (RCC_APB1ENR_USART4EN_SHIFT))
#define RCC_APB1ENR_LPUART1EN_SHIFT	18
#define RCC_APB1ENR_LPUART1EN_MASK	(1 << (RCC_APB1ENR_LPUART1EN_SHIFT))
#define RCC_APB1ENR_LPUART1EN_NO	(0 << (RCC_APB1ENR_LPUART1EN_SHIFT))
#define RCC_APB1ENR_LPUART1EN_YES	(1 << (RCC_APB1ENR_LPUART1EN_SHIFT))
#define RCC_APB1ENR_USART2EN_SHIFT	17
#define RCC_APB1ENR_USART2EN_MASK	(1 << (RCC_APB1ENR_USART2EN_SHIFT))
#define RCC_APB1ENR_USART2EN_NO         (0 << (RCC_APB1ENR_USART2EN_SHIFT))
#define RCC_APB1ENR_USART2EN_YES	(1 << (RCC_APB1ENR_USART2EN_SHIFT))
#define RCC_APB1ENR_SPI2EN_SHIFT	14
#define RCC_APB1ENR_SPI2EN_MASK         (1 << (RCC_APB1ENR_SPI2EN_SHIFT))
#define RCC_APB1ENR_SPI2EN_NO		(0 << (RCC_APB1ENR_SPI2EN_SHIFT))
#define RCC_APB1ENR_SPI2EN_YES		(1 << (RCC_APB1ENR_SPI2EN_SHIFT))
#define RCC_APB1ENR_WWDGEN_SHIFT	11
#define RCC_APB1ENR_WWDGEN_MASK         (1 << (RCC_APB1ENR_WWDGEN_SHIFT))
#define RCC_APB1ENR_WWDGEN_NO		(0 << (RCC_APB1ENR_WWDGEN_SHIFT))
#define RCC_APB1ENR_WWDGEN_YES		(1 << (RCC_APB1ENR_WWDGEN_SHIFT))
#define RCC_APB1ENR_RTCAPBEN_SHIFT	10
#define RCC_APB1ENR_RTCAPBEN_MASK	(1 << (RCC_APB1ENR_RTCAPBEN_SHIFT))
#define RCC_APB1ENR_RTCAPBEN_NO         (0 << (RCC_APB1ENR_RTCAPBEN_SHIFT))
#define RCC_APB1ENR_RTCAPBEN_YES	(1 << (RCC_APB1ENR_RTCAPBEN_SHIFT))
#define RCC_APB1ENR_LEDEN_SHIFT         9
#define RCC_APB1ENR_LEDEN_MASK		(1 << (RCC_APB1ENR_LEDEN_SHIFT))
#define RCC_APB1ENR_LEDEN_NO		(0 << (RCC_APB1ENR_LEDEN_SHIFT))
#define RCC_APB1ENR_LEDEN_YES		(1 << (RCC_APB1ENR_LEDEN_SHIFT))
#define RCC_APB1ENR_TIM7EN_SHIFT	5
#define RCC_APB1ENR_TIM7EN_MASK         (1 << (RCC_APB1ENR_TIM7EN_SHIFT))
#define RCC_APB1ENR_TIM7EN_NO		(0 << (RCC_APB1ENR_TIM7EN_SHIFT))
#define RCC_APB1ENR_TIM7EN_YES		(1 << (RCC_APB1ENR_TIM7EN_SHIFT))
#define RCC_APB1ENR_TIM6EN_SHIFT	4
#define RCC_APB1ENR_TIM6EN_MASK         (1 << (RCC_APB1ENR_TIM6EN_SHIFT))
#define RCC_APB1ENR_TIM6EN_NO		(0 << (RCC_APB1ENR_TIM6EN_SHIFT))
#define RCC_APB1ENR_TIM6EN_YES		(1 << (RCC_APB1ENR_TIM6EN_SHIFT))
#define RCC_APB1ENR_TIM3EN_SHIFT	1
#define RCC_APB1ENR_TIM3EN_MASK         (1 << (RCC_APB1ENR_TIM3EN_SHIFT))
#define RCC_APB1ENR_TIM3EN_NO		(0 << (RCC_APB1ENR_TIM3EN_SHIFT))
#define RCC_APB1ENR_TIM3EN_YES		(1 << (RCC_APB1ENR_TIM3EN_SHIFT))
#define RCC_APB1ENR_TIM2EN_SHIFT	0
#define RCC_APB1ENR_TIM2EN_MASK         (1 << (RCC_APB1ENR_TIM2EN_SHIFT))
#define RCC_APB1ENR_TIM2EN_NO		(0 << (RCC_APB1ENR_TIM2EN_SHIFT))
#define RCC_APB1ENR_TIM2EN_YES		(1 << (RCC_APB1ENR_TIM2EN_SHIFT))

  __IO uint32_t         IOPSMENR;       /* 0x3c */
  __IO uint32_t         AHBSMENR;       /* 0x40 */
  __IO uint32_t         APB2SMENR;      /* 0x44 */
  __IO uint32_t         APB1SMENR;      /* 0x48 */

  __IO uint32_t         CCIPR;          /* 0x4c */
#define RCC_CCIPR_CLK48SEL_SHIFT        26
#define RCC_CCIPR_CLK48SEL_MASK         (1 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_CLK48SEL_PLL          (0 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_CLK48SEL_HSI48        (1 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_SHIFT       18
#define RCC_CCIPR_LPTIM1SEL_MASK        (3 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_PCLK        (0 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_LSI         (1 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_HSI16       (2 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_LSE         (3 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_SHIFT         16
#define RCC_CCIPR_I2C3SEL_MASK          (3 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_PCLK          (0 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_SYSCLK        (1 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_HSI16         (2 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_RESERVED3     (3 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_SHIFT         12
#define RCC_CCIPR_I2C1SEL_MASK          (3 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_PCLK          (0 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_SYSCLK        (1 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_HSI16         (2 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_RESERVED3     (3 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_SHIFT      10
#define RCC_CCIPR_LPUART1SEL_MASK       (3 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_PCLK       (0 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_SYSCLK     (1 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_HSI16      (2 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_LSE        (3 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_SHIFT       2
#define RCC_CCIPR_USART2SEL_MASK        (3 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_PCLK        (0 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_SYSCLK      (1 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_HSI16       (2 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_LSE         (3 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_SHIFT       0
#define RCC_CCIPR_USART1SEL_MASK        (3 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_PCLK        (0 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_SYSCLK      (1 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_HSI16       (2 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_LSE         (3 << (RCC_CCIPR_USART1SEL_SHIFT))

  __IO uint32_t                 CSR;    /* 0x50 */
#define RCC_CSR_LPWRRSTF_SHIFT		31
#define RCC_CSR_LPWRRSTF_MASK		(1 << (RCC_CSR_LPWRRSTF_SHIFT))
#define RCC_CSR_LPWRRSTF_NO		(0 << (RCC_CSR_LPWRRSTF_SHIFT))
#define RCC_CSR_LPWRRSTF_YES		(1 << (RCC_CSR_LPWRRSTF_SHIFT))
#define RCC_CSR_WWDGRSTF_SHIFT		30
#define RCC_CSR_WWDGRSTF_MASK		(1 << (RCC_CSR_WWDGRSTF_SHIFT))
#define RCC_CSR_WWDGRSTF_NO		(0 << (RCC_CSR_WWDGRSTF_SHIFT))
#define RCC_CSR_WWDGRSTF_YES		(1 << (RCC_CSR_WWDGRSTF_SHIFT))
#define RCC_CSR_IWWGRSTF_SHIFT		29
#define RCC_CSR_IWWGRSTF_MASK		(1 << (RCC_CSR_IWWGRSTF_SHIFT))
#define RCC_CSR_IWWGRSTF_NO		(0 << (RCC_CSR_IWWGRSTF_SHIFT))
#define RCC_CSR_IWWGRSTF_YES		(1 << (RCC_CSR_IWWGRSTF_SHIFT))
#define RCC_CSR_SFTRSTF_SHIFT		28
#define RCC_CSR_SFTRSTF_MASK		(1 << (RCC_CSR_SFTRSTF_SHIFT))
#define RCC_CSR_SFTRSTF_NO		(0 << (RCC_CSR_SFTRSTF_SHIFT))
#define RCC_CSR_SFTRSTF_YES		(1 << (RCC_CSR_SFTRSTF_SHIFT))
#define RCC_CSR_PORRSTF_SHIFT		27
#define RCC_CSR_PORRSTF_MASK		(1 << (RCC_CSR_PORRSTF_SHIFT))
#define RCC_CSR_PORRSTF_NO		(0 << (RCC_CSR_PORRSTF_SHIFT))
#define RCC_CSR_PORRSTF_YES		(1 << (RCC_CSR_PORRSTF_SHIFT))
#define RCC_CSR_PINRSTF_SHIFT		26
#define RCC_CSR_PINRSTF_MASK		(1 << (RCC_CSR_PINRSTF_SHIFT))
#define RCC_CSR_PINRSTF_NO		(0 << (RCC_CSR_PINRSTF_SHIFT))
#define RCC_CSR_PINRSTF_YES		(1 << (RCC_CSR_PINRSTF_SHIFT))
#define RCC_CSR_OBLRSTF_SHIFT		25
#define RCC_CSR_OBLRSTF_MASK		(1 << (RCC_CSR_OBLRSTF_SHIFT))
#define RCC_CSR_OBLRSTF_NO		(0 << (RCC_CSR_OBLRSTF_SHIFT))
#define RCC_CSR_OBLRSTF_YES		(1 << (RCC_CSR_OBLRSTF_SHIFT))
#define RCC_CSR_FWRSTF_SHIFT		24
#define RCC_CSR_FWRSTF_MASK		(1 << (RCC_CSR_FWRSTF_SHIFT))
#define RCC_CSR_FWRSTF_NO		(0 << (RCC_CSR_FWRSTF_SHIFT))
#define RCC_CSR_FWRSTF_YES              (1 << (RCC_CSR_FWRSTF_SHIFT))
#define RCC_CSR_RMVF_SHIFT              23
#define RCC_CSR_RMVF_MASK               (1 << (RCC_CSR_RMVF_SHIFT))
#define RCC_CSR_RMVF_NO                 (0 << (RCC_CSR_RMVF_SHIFT))
#define RCC_CSR_RMVF_YES                (1 << (RCC_CSR_RMVF_SHIFT))
#define RCC_CSR_CSSLSED_SHIFT           14
#define RCC_CSR_CSSLSED_MASK            (1 << (RCC_CSR_CSSLSED_SHIFT))
#define RCC_CSR_CSSLSED_NO              (0 << (RCC_CSR_CSSLSED_SHIFT))
#define RCC_CSR_CSSLSED_YES             (1 << (RCC_CSR_CSSLSED_SHIFT))
#define RCC_CSR_CSSLSEON_SHIFT          13
#define RCC_CSR_CSSLSEON_MASK           (1 << (RCC_CSR_CSSLSEON_SHIFT))
#define RCC_CSR_CSSLSEON_NO             (0 << (RCC_CSR_CSSLSEON_SHIFT))
#define RCC_CSR_CSSLSEON_YES            (1 << (RCC_CSR_CSSLSEON_SHIFT))
#define RCC_CSR_LSEDRV_SHIFT            11
#define RCC_CSR_LSEDRV_MASK             (3 << (RCC_CSR_LSEDRV_SHIFT))
#define RCC_CSR_LSEDRV_LOWEST           (0 << (RCC_CSR_LSEDRV_SHIFT))
#define RCC_CSR_LSEDRV_MEDLOW           (1 << (RCC_CSR_LSEDRV_SHIFT))
#define RCC_CSR_LSEDRV_MEDHIGH          (2 << (RCC_CSR_LSEDRV_SHIFT))
#define RCC_CSR_LSEDRV_HIGHEST          (3 << (RCC_CSR_LSEDRV_SHIFT))
#define RCC_CSR_LSEBYP_SHIFT            10
#define RCC_CSR_LSEBYP_MASK             (1 << (RCC_CSR_LSEBYP_SHIFT))
#define RCC_CSR_LSEBYP_NO               (0 << (RCC_CSR_LSEBYP_SHIFT))
#define RCC_CSR_LSEBYP_YES              (1 << (RCC_CSR_LSEBYP_SHIFT))
#define RCC_CSR_LSERDY_SHIFT            9
#define RCC_CSR_LSERDY_MASK             (1 << (RCC_CSR_LSERDY_SHIFT))
#define RCC_CSR_LSERDY_NO               (0 << (RCC_CSR_LSERDY_SHIFT))
#define RCC_CSR_LSERDY_YES              (1 << (RCC_CSR_LSERDY_SHIFT))
#define RCC_CSR_LSEON_SHIFT             8
#define RCC_CSR_LSEON_MASK              (1 << (RCC_CSR_LSEON_SHIFT))
#define RCC_CSR_LSEON_NO                (0 << (RCC_CSR_LSEON_SHIFT))
#define RCC_CSR_LSEON_YES               (1 << (RCC_CSR_LSEON_SHIFT))
#define RCC_CSR_LSIRDY_SHIFT            1
#define RCC_CSR_LSIRDY_MASK             (1 << (RCC_CSR_LSIRDY_SHIFT))
#define RCC_CSR_LSIRDY_NO               (0 << (RCC_CSR_LSIRDY_SHIFT))
#define RCC_CSR_LSIRDY_YES              (1 << (RCC_CSR_LSIRDY_SHIFT))
#define RCC_CSR_LSION_SHIFT             0
#define RCC_CSR_LSION_MASK              (1 << (RCC_CSR_LSION_SHIFT))
#define RCC_CSR_LSION_NO                (0 << (RCC_CSR_LSION_SHIFT))
#define RCC_CSR_LSION_YES               (1 << (RCC_CSR_LSION_SHIFT))

} stm32Dev_RCC;

#endif
