/*
 * Copyright (c) 2018 zhtlab
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit
 * persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef _STM32L4RCC_H_
#define _STM32L4RCC_H_

/* STM32L433 reference manual  DocID027295 Rev 3 */

#define RCC_CLOCK_HPRETABLE     {0, 0, 0, 0,  0, 0, 0, 0,  1, 2, 3, 4,  6, 7, 8, 9}
#define RCC_CLOCK_PPRETABLE     {0, 0, 0, 0,  1, 2, 3, 4}
typedef struct {
  __IO uint32_t         CR;             /* 0x00 */
#define RCC_CR_PLLSAI1RDY_SHIFT         27
#define RCC_CR_PLLSAI1RDY_MASK          (1 << (RCC_CR_PLLSAI1RDY_SHIFT))
#define RCC_CR_PLLSAI1RDY_NO            (0 << (RCC_CR_PLLSAI1RDY_SHIFT))
#define RCC_CR_PLLSAI1RDY_YES		(1 << (RCC_CR_PLLSAI1RDY_SHIFT))
#define RCC_CR_PLLSAI1ON_SHIFT		26
#define RCC_CR_PLLSAI1ON_MASK		(1 << (RCC_CR_PLLSAI1ON_SHIFT))
#define RCC_CR_PLLSAI1ON_NO		(0 << (RCC_CR_PLLSAI1ON_SHIFT))
#define RCC_CR_PLLSAI1ON_YES		(1 << (RCC_CR_PLLSAI1ON_SHIFT))
#define RCC_CR_PLLRDY_SHIFT		25
#define RCC_CR_PLLRDY_MASK		(1 << (RCC_CR_PLLRDY_SHIFT))
#define RCC_CR_PLLRDY_NO		(0 << (RCC_CR_PLLRDY_SHIFT))
#define RCC_CR_PLLRDY_YES		(1 << (RCC_CR_PLLRDY_SHIFT))
#define RCC_CR_PLLON_SHIFT		24
#define RCC_CR_PLLON_MASK		(1 << (RCC_CR_PLLON_SHIFT))
#define RCC_CR_PLLON_NO                 (0 << (RCC_CR_PLLON_SHIFT))
#define RCC_CR_PLLON_YES		(1 << (RCC_CR_PLLON_SHIFT))
#define RCC_CR_CSSON_SHIFT		19
#define RCC_CR_CSSON_MASK		(1 << (RCC_CR_CSSON_SHIFT))
#define RCC_CR_CSSON_NO                 (0 << (RCC_CR_CSSON_SHIFT))
#define RCC_CR_CSSON_YES		(1 << (RCC_CR_CSSON_SHIFT))
#define RCC_CR_HSEBYP_SHIFT		18
#define RCC_CR_HSEBYP_MASK		(1 << (RCC_CR_HSEBYP_SHIFT))
#define RCC_CR_HSEBYP_NO		(0 << (RCC_CR_HSEBYP_SHIFT))
#define RCC_CR_HSEBYP_YES		(1 << (RCC_CR_HSEBYP_SHIFT))
#define RCC_CR_HSERDY_SHIFT		17
#define RCC_CR_HSERDY_MASK		(1 << (RCC_CR_HSERDY_SHIFT))
#define RCC_CR_HSERDY_NO		(0 << (RCC_CR_HSERDY_SHIFT))
#define RCC_CR_HSERDY_YES		(1 << (RCC_CR_HSERDY_SHIFT))
#define RCC_CR_HSEON_SHIFT		16
#define RCC_CR_HSEON_MASK		(1 << (RCC_CR_HSEON_SHIFT))
#define RCC_CR_HSEON_NO                 (0 << (RCC_CR_HSEON_SHIFT))
#define RCC_CR_HSEON_YES		(1 << (RCC_CR_HSEON_SHIFT))
#define RCC_CR_HSIASFS_SHIFT		11
#define RCC_CR_HSIASFS_MASK		(1 << (RCC_CR_HSIASFS_SHIFT))
#define RCC_CR_HSIASFS_NO		(0 << (RCC_CR_HSIASFS_SHIFT))
#define RCC_CR_HSIASFS_YES		(1 << (RCC_CR_HSIASFS_SHIFT))
#define RCC_CR_HSIRDY_SHIFT		10
#define RCC_CR_HSIRDY_MASK		(1 << (RCC_CR_HSIRDY_SHIFT))
#define RCC_CR_HSIRDY_NO		(0 << (RCC_CR_HSIRDY_SHIFT))
#define RCC_CR_HSIRDY_YES		(1 << (RCC_CR_HSIRDY_SHIFT))
#define RCC_CR_HSIKERON_SHIFT		9
#define RCC_CR_HSIKERON_MASK		(1 << (RCC_CR_HSIKERON_SHIFT))
#define RCC_CR_HSIKERON_NO		(0 << (RCC_CR_HSIKERON_SHIFT))
#define RCC_CR_HSIKERON_YES		(1 << (RCC_CR_HSIKERON_SHIFT))
#define RCC_CR_HSION_SHIFT		8
#define RCC_CR_HSION_MASK		(1 << (RCC_CR_HSION_SHIFT))
#define RCC_CR_HSION_NO                 (0 << (RCC_CR_HSION_SHIFT))
#define RCC_CR_HSION_YES		(1 << (RCC_CR_HSION_SHIFT))
#define RCC_CR_MSIRANGE_SHIFT		4
#define RCC_CR_MSIRANGE_MASK		(0xf << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_100KHZ		(0 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_200KHZ		(1 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_400KHZ		(2 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_800KHZ		(3 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_1MHZ		(4 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_2MHZ		(5 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_4MHZ		(6 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_8MHZ		(7 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_16MHZ		(8 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_24MHZ		(9 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_32MHZ		(10 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRANGE_48MHZ		(11 << (RCC_CR_MSIRANGE_SHIFT))
#define RCC_CR_MSIRGSEL_SHIFT		3
#define RCC_CR_MSIRGSEL_MASK		(1 << (RCC_CR_MSIRGSEL_SHIFT))
#define RCC_CR_MSIRGSEL_CSR		(0 << (RCC_CR_MSIRGSEL_SHIFT))
#define RCC_CR_MSIRGSEL_CR		(1 << (RCC_CR_MSIRGSEL_SHIFT))
#define RCC_CR_MSIPLLEN_SHIFT		2
#define RCC_CR_MSIPLLEN_MASK		(1 << (RCC_CR_MSIPLLEN_SHIFT))
#define RCC_CR_MSIPLLEN_NO		(0 << (RCC_CR_MSIPLLEN_SHIFT))
#define RCC_CR_MSIPLLEN_YES		(1 << (RCC_CR_MSIPLLEN_SHIFT))
#define RCC_CR_MSIRDY_SHIFT		1
#define RCC_CR_MSIRDY_MASK		(1 << (RCC_CR_MSIRDY_SHIFT))
#define RCC_CR_MSIRDY_NO		(0 << (RCC_CR_MSIRDY_SHIFT))
#define RCC_CR_MSIRDY_YES		(1 << (RCC_CR_MSIRDY_SHIFT))
#define RCC_CR_MSION_SHIFT		0
#define RCC_CR_MSION_MASK		(1 << (RCC_CR_MSION_SHIFT))
#define RCC_CR_MSION_NO                 (0 << (RCC_CR_MSION_SHIFT))
#define RCC_CR_MSION_YES                (1 << (RCC_CR_MSION_SHIFT))

  __IO uint32_t         ICSCR;          /* 0x04 */
#define RCC_ICSCR_HSITRIM_SHIFT         24
#define RCC_ICSCR_HSITRIM_MASK          (0x1f << (RCC_ICSCR_HSITRIM_SHIFT))
#define RCC_ICSCR_HSICAL_SHIFT          16
#define RCC_ICSCR_HSICAL_MASK           (0xff << (RCC_ICSCR_HSICAL_SHIFT))
#define RCC_ICSCR_MSITRIM_SHIFT         24
#define RCC_ICSCR_MSITRIM_MASK          (0x1f << (RCC_ICSCR_MSITRIM_SHIFT))
#define RCC_ICSCR_MSICAL_SHIFT          16
#define RCC_ICSCR_MSICAL_MASK           (0xff << (RCC_ICSCR_MSICAL_SHIFT))

  __IO uint32_t         CFGR;           /* 0x08 */
#define RCC_CFGR_MCOPRE_SHIFT           28
#define RCC_CFGR_MCOPRE_MASK            (7 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV1            (0 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV2            (1 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV4		(2 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV7		(3 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOPRE_DIV16		(4 << (RCC_CFGR_MCOPRE_SHIFT))
#define RCC_CFGR_MCOSEL_SHIFT		24
#define RCC_CFGR_MCOSEL_MASK		(0xf << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_DISABLE		(0 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_SYSCLK		(1 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_MSI		(2 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_HSI6		(3 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_HSE		(4 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_MAINPLL		(5 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_LSI		(6 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_MCOSEL_HSI48		(8 << (RCC_CFGR_MCOSEL_SHIFT))
#define RCC_CFGR_STOPWUCK_SHIFT		16
#define RCC_CFGR_STOPWUCK_MASK		(1 << (RCC_CFGR_STOPWUCK_SHIFT))
#define RCC_CFGR_STOPWUCK_NO		(0 << (RCC_CFGR_STOPWUCK_SHIFT))
#define RCC_CFGR_STOPWUCK_YES		(1 << (RCC_CFGR_STOPWUCK_SHIFT))
#define RCC_CFGR_PPRE2_SHIFT		11		/* APB2 */
#define RCC_CFGR_PPRE2_MASK		(7 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV1		(0 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV2		(4 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV4		(5 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV8		(6 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE2_DIV16		(7 << (RCC_CFGR_PPRE2_SHIFT))
#define RCC_CFGR_PPRE1_SHIFT		8		/* APB1 */
#define RCC_CFGR_PPRE1_MASK		(7 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV1		(0 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV2		(4 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV4		(5 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV8		(6 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_PPRE1_DIV16		(7 << (RCC_CFGR_PPRE1_SHIFT))
#define RCC_CFGR_HPRE_SHIFT             4               /* AHB */
#define RCC_CFGR_HPRE_MASK		(0xf << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV1		(0 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV2		(8 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV4		(9 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV8		(10 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV16             (11 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV64             (12 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV128            (13 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV256            (14 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_HPRE_DIV512            (15 << (RCC_CFGR_HPRE_SHIFT))
#define RCC_CFGR_SWS_SHIFT              2
#define RCC_CFGR_SWS_MASK               (3 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_MSI                (0 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_HSI                (1 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_HSE                (2 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SWS_PLL                (3 << (RCC_CFGR_SWS_SHIFT))
#define RCC_CFGR_SW_SHIFT               0
#define RCC_CFGR_SW_MASK                (3 << (RCC_CFGR_SW_SHIFT))
#define RCC_CFGR_SW_MSI                 (0 << (RCC_CFGR_SW_SHIFT))
#define RCC_CFGR_SW_HSI                 (1 << (RCC_CFGR_SW_SHIFT))
#define RCC_CFGR_SW_HSE                 (2 << (RCC_CFGR_SW_SHIFT))
#define RCC_CFGR_SW_PLL                 (3 << (RCC_CFGR_SW_SHIFT))

  __IO uint32_t         PLLCFGR;        /* 0x0c */
#define RCC_PLLCFGR_PLLPDIV_SHIFT       27
#define RCC_PLLCFGR_PLLPDIV_MASK        (3 << (RCC_PLLCFGR_PLLPDIV_SHIFT))
#define RCC_PLLCFGR_PLLPDIV_PLLP        (0 << (RCC_PLLCFGR_PLLPDIV_SHIFT))
#define RCC_PLLCFGR_PLLPDIV_VCODIV2     (2 << (RCC_PLLCFGR_PLLPDIV_SHIFT))
#define RCC_PLLCFGR_PLLPDIV_VCODIV3     (3 << (RCC_PLLCFGR_PLLPDIV_SHIFT))
#define RCC_PLLCFGR_PLLPDIV_VCODIV31    (3 << (RCC_PLLCFGR_PLLPDIV_SHIFT))
#define RCC_PLLCFGR_PLLR_SHIFT          25
#define RCC_PLLCFGR_PLLR_MASK           (3 << (RCC_PLLCFGR_PLLR_SHIFT))
#define RCC_PLLCFGR_PLLR_DIV2		(0 << (RCC_PLLCFGR_PLLR_SHIFT))
#define RCC_PLLCFGR_PLLR_DIV4		(1 << (RCC_PLLCFGR_PLLR_SHIFT))
#define RCC_PLLCFGR_PLLR_DIV6		(2 << (RCC_PLLCFGR_PLLR_SHIFT))
#define RCC_PLLCFGR_PLLR_DIV8		(3 << (RCC_PLLCFGR_PLLR_SHIFT))
#define RCC_PLLCFGR_PLLREN_SHIFT        24
#define RCC_PLLCFGR_PLLREN_MASK		(1 << (RCC_PLLCFGR_PLLREN_SHIFT))
#define RCC_PLLCFGR_PLLREN_NO		(0 << (RCC_PLLCFGR_PLLREN_SHIFT))
#define RCC_PLLCFGR_PLLREN_YES		(1 << (RCC_PLLCFGR_PLLREN_SHIFT))
#define RCC_PLLCFGR_PLLQ_SHIFT		21
#define RCC_PLLCFGR_PLLQ_MASK		(3 << (RCC_PLLCFGR_PLLQ_SHIFT))
#define RCC_PLLCFGR_PLLQ_DIV2		(0 << (RCC_PLLCFGR_PLLQ_SHIFT))
#define RCC_PLLCFGR_PLLQ_DIV4		(1 << (RCC_PLLCFGR_PLLQ_SHIFT))
#define RCC_PLLCFGR_PLLQ_DIV6		(2 << (RCC_PLLCFGR_PLLQ_SHIFT))
#define RCC_PLLCFGR_PLLQ_DIV8		(3 << (RCC_PLLCFGR_PLLQ_SHIFT))
#define RCC_PLLCFGR_PLLQEN_SHIFT	20
#define RCC_PLLCFGR_PLLQEN_MASK		(1 << (RCC_PLLCFGR_PLLQEN_SHIFT))
#define RCC_PLLCFGR_PLLQEN_NO		(0 << (RCC_PLLCFGR_PLLQEN_SHIFT))
#define RCC_PLLCFGR_PLLQEN_YES		(1 << (RCC_PLLCFGR_PLLQEN_SHIFT))
#define RCC_PLLCFGR_PLLP_SHIFT		17
#define RCC_PLLCFGR_PLLP_MASK		(1 << (RCC_PLLCFGR_PLLP_SHIFT))
#define RCC_PLLCFGR_PLLP_DIV7		(0 << (RCC_PLLCFGR_PLLP_SHIFT))
#define RCC_PLLCFGR_PLLP_DIV17		(1 << (RCC_PLLCFGR_PLLP_SHIFT))
#define RCC_PLLCFGR_PLLPEN_SHIFT	16
#define RCC_PLLCFGR_PLLPEN_MASK		(1 << (RCC_PLLCFGR_PLLPEN_SHIFT))
#define RCC_PLLCFGR_PLLPEN_NO		(0 << (RCC_PLLCFGR_PLLPEN_SHIFT))
#define RCC_PLLCFGR_PLLPEN_YES		(1 << (RCC_PLLCFGR_PLLPEN_SHIFT))
#define RCC_PLLCFGR_PLLN_SHIFT		8
#define RCC_PLLCFGR_PLLN_MASK		(0x7f << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MULX(x)	(((x) & 0x7f) << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL0_XXX	(0 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL1_XXX	(2 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL7_XXX	(7 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL8		(8 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL9		(9 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL86		(86 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL97_XXX      (87 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLN_MUL127_XXX     (127 << (RCC_PLLCFGR_PLLN_SHIFT))
#define RCC_PLLCFGR_PLLM_SHIFT		4
#define RCC_PLLCFGR_PLLM_MASK		(7 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV1		(0 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV2		(1 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV3		(2 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV4		(3 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV5		(4 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV6		(5 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV7		(6 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLM_DIV8		(7 << (RCC_PLLCFGR_PLLM_SHIFT))
#define RCC_PLLCFGR_PLLSRC_SHIFT	0
#define RCC_PLLCFGR_PLLSRC_MASK		(3 << (RCC_PLLCFGR_PLLSRC_SHIFT))
#define RCC_PLLCFGR_PLLSRC_NONE         (0 << (RCC_PLLCFGR_PLLSRC_SHIFT))
#define RCC_PLLCFGR_PLLSRC_MSI		(1 << (RCC_PLLCFGR_PLLSRC_SHIFT))
#define RCC_PLLCFGR_PLLSRC_HSI16	(2 << (RCC_PLLCFGR_PLLSRC_SHIFT))
#define RCC_PLLCFGR_PLLSRC_HSE		(3 << (RCC_PLLCFGR_PLLSRC_SHIFT))
  __IO uint32_t         PLLSAI1CFGR;    /* 0x10 */
  __IO uint32_t         reserved0x14;   /* 0x14 */
  __IO uint32_t         CIER;           /* 0x1c */
#define RCC_CIER_HSI48_RDYIE_SHIFT      10
#define RCC_CIER_HSI48_RDYIE_MASK	(1 << (RCC_CIER_HSI48_RDYIE_SHIFT))
#define RCC_CIER_HSI48_RDYIE_NO		(0 << (RCC_CIER_HSI48_RDYIE_SHIFT))
#define RCC_CIER_HSI48_RDYIE_YES	(1 << (RCC_CIER_HSI48_RDYIE_SHIFT))
#define RCC_CIER_LSE_CSSIE_SHIFT	9
#define RCC_CIER_LSE_CSSIE_MASK		(1 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSE_CSSIE_NO		(0 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSE_CSSIE_YES		(1 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_PLLSAI1_RDYIE_SHIFT	6
#define RCC_CIER_PLLSAI1_RDYIE_MASK	(1 << (RCC_CIER_PLLSAI1_RDYIE_SHIFT))
#define RCC_CIER_PLLSAI1_RDYIE_NO	(0 << (RCC_CIER_PLLSAI1_RDYIE_SHIFT))
#define RCC_CIER_PLLSAI1_RDYIE_YES	(1 << (RCC_CIER_PLLSAI1_RDYIE_SHIFT))
#define RCC_CIER_PLL_RDYIE_SHIFT	5
#define RCC_CIER_PLL_RDYIE_MASK		(1 << (RCC_CIER_PLL_RDYIE_SHIFT))
#define RCC_CIER_PLL_RDYIE_NO		(0 << (RCC_CIER_PLL_RDYIE_SHIFT))
#define RCC_CIER_PLL_RDYIE_YES		(1 << (RCC_CIER_PLL_RDYIE_SHIFT))
#define RCC_CIER_HSE_RDYIE_SHIFT	4
#define RCC_CIER_HSE_RDYIE_MASK		(1 << (RCC_CIER_HSE_RDYIE_SHIFT))
#define RCC_CIER_HSE_RDYIE_NO		(0 << (RCC_CIER_HSE_RDYIE_SHIFT))
#define RCC_CIER_HSE_RDYIE_YES		(1 << (RCC_CIER_HSE_RDYIE_SHIFT))
#define RCC_CIER_HSI_RDYIE_SHIFT	3
#define RCC_CIER_HSI_RDYIE_MASK		(1 << (RCC_CIER_HSI_RDYIE_SHIFT))
#define RCC_CIER_HSI_RDYIE_NO		(0 << (RCC_CIER_HSI_RDYIE_SHIFT))
#define RCC_CIER_HSI_RDYIE_YES		(1 << (RCC_CIER_HSI_RDYIE_SHIFT))
#define RCC_CIER_MSI_RDYIE_SHIFT	2
#define RCC_CIER_MSI_RDYIE_MASK		(1 << (RCC_CIER_MSI_RDYIE_SHIFT))
#define RCC_CIER_MSI_RDYIE_NO		(0 << (RCC_CIER_MSI_RDYIE_SHIFT))
#define RCC_CIER_MSI_RDYIE_YES		(1 << (RCC_CIER_MSI_RDYIE_SHIFT))
#define RCC_CIER_LSE_RDYIE_SHIFT	1
#define RCC_CIER_LSE_RDYIE_MASK		(1 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSE_RDYIE_NO		(0 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSE_RDYIE_YES		(1 << (RCC_CIER_LSE_RDYIE_SHIFT))
#define RCC_CIER_LSI_RDYIE_SHIFT	0
#define RCC_CIER_LSI_RDYIE_MASK		(1 << (RCC_CIER_LSI_RDYIE_SHIFT))
#define RCC_CIER_LSI_RDYIE_NO		(0 << (RCC_CIER_LSI_RDYIE_SHIFT))
#define RCC_CIER_LSI_RDYIE_YES		(1 << (RCC_CIER_LSI_RDYIE_SHIFT))

  __IO uint32_t         CIFR;           /* 0x1c */
#define RCC_CIFR_HSI48_RDYF_SHIFT	10
#define RCC_CIFR_HSI48_RDYF_MASK	(1 << (RCC_CIFR_HSI48_RDYF_SHIFT))
#define RCC_CIFR_HSI48_RDYF_NO		(0 << (RCC_CIFR_HSI48_RDYF_SHIFT))
#define RCC_CIFR_HSI48_RDYF_YES		(1 << (RCC_CIFR_HSI48_RDYF_SHIFT))
#define RCC_CIFR_LSE_CSSF_SHIFT		9
#define RCC_CIFR_LSE_CSSF_MASK		(1 << (RCC_CIFR_LSE_CSSF_SHIFT))
#define RCC_CIFR_LSE_CSSF_NO		(0 << (RCC_CIFR_LSE_CSSF_SHIFT))
#define RCC_CIFR_LSE_CSSF_YES		(1 << (RCC_CIFR_LSE_CSSF_SHIFT))
#define RCC_CIFR_CSSF_SHIFT		8
#define RCC_CIFR_CSSF_MASK		(1 << (RCC_CIFR_LSE_CSSF_SHIFT))
#define RCC_CIFR_CSSF_NO		(0 << (RCC_CIFR_LSE_CSSF_SHIFT))
#define RCC_CIFR_CSSF_YES		(1 << (RCC_CIFR_LSE_CSSF_SHIFT))
#define RCC_CIFR_PLLSAI1_RDYF_SHIFT	6
#define RCC_CIFR_PLLSAI1_RDYF_MASK	(1 << (RCC_CIFR_PLLSAI1_RDYF_SHIFT))
#define RCC_CIFR_PLLSAI1_RDYF_NO	(0 << (RCC_CIFR_PLLSAI1_RDYF_SHIFT))
#define RCC_CIFR_PLLSAI1_RDYF_YES	(1 << (RCC_CIFR_PLLSAI1_RDYF_SHIFT))
#define RCC_CIFR_PLL_RDYF_SHIFT		5
#define RCC_CIFR_PLL_RDYF_MASK		(1 << (RCC_CIFR_PLL_RDYF_SHIFT))
#define RCC_CIFR_PLL_RDYF_NO		(0 << (RCC_CIFR_PLL_RDYF_SHIFT))
#define RCC_CIFR_PLL_RDYF_YES		(1 << (RCC_CIFR_PLL_RDYF_SHIFT))
#define RCC_CIFR_HSE_RDYF_SHIFT		4
#define RCC_CIFR_HSE_RDYF_MASK		(1 << (RCC_CIFR_HSE_RDYF_SHIFT))
#define RCC_CIFR_HSE_RDYF_NO		(0 << (RCC_CIFR_HSE_RDYF_SHIFT))
#define RCC_CIFR_HSE_RDYF_YES		(1 << (RCC_CIFR_HSE_RDYF_SHIFT))
#define RCC_CIFR_HSI_RDYF_SHIFT		3
#define RCC_CIFR_HSI_RDYF_MASK		(1 << (RCC_CIFR_HSI_RDYF_SHIFT))
#define RCC_CIFR_HSI_RDYF_NO		(0 << (RCC_CIFR_HSI_RDYF_SHIFT))
#define RCC_CIFR_HSI_RDYF_YES		(1 << (RCC_CIFR_HSI_RDYF_SHIFT))
#define RCC_CIFR_MSI_RDYF_SHIFT		2
#define RCC_CIFR_MSI_RDYF_MASK		(1 << (RCC_CIFR_MSI_RDYF_SHIFT))
#define RCC_CIFR_MSI_RDYF_NO		(0 << (RCC_CIFR_MSI_RDYF_SHIFT))
#define RCC_CIFR_MSI_RDYF_YES		(1 << (RCC_CIFR_MSI_RDYF_SHIFT))
#define RCC_CIFR_LSE_RDYF_SHIFT		1
#define RCC_CIFR_LSE_RDYF_MASK		(1 << (RCC_CIFR_LSE_RDYF_SHIFT))
#define RCC_CIFR_LSE_RDYF_NO		(0 << (RCC_CIFR_LSE_RDYF_SHIFT))
#define RCC_CIFR_LSE_RDYF_YES		(1 << (RCC_CIFR_LSE_RDYF_SHIFT))
#define RCC_CIFR_LSI_RDYF_SHIFT		0
#define RCC_CIFR_LSI_RDYF_MASK		(1 << (RCC_CIFR_LSI_RDYF_SHIFT))
#define RCC_CIFR_LSI_RDYF_NO		(0 << (RCC_CIFR_LSI_RDYF_SHIFT))
#define RCC_CIFR_LSI_RDYF_YES		(1 << (RCC_CIFR_LSI_RDYF_SHIFT))
  __IO uint32_t         CICR;           /* 0x20 */
#define RCC_CICR_HSI48_RDYC_SHIFT	10
#define RCC_CICR_HSI48_RDYC_MASK	(1 << (RCC_CICR_HSI48_RDYC_SHIFT))
#define RCC_CICR_HSI48_RDYC_NO		(0 << (RCC_CICR_HSI48_RDYC_SHIFT))
#define RCC_CICR_HSI48_RDYC_YES		(1 << (RCC_CICR_HSI48_RDYC_SHIFT))
#define RCC_CICR_LSE_CSSC_SHIFT		9
#define RCC_CICR_LSE_CSSC_MASK		(1 << (RCC_CICR_LSE_CSSC_SHIFT))
#define RCC_CICR_LSE_CSSC_NO		(0 << (RCC_CICR_LSE_CSSC_SHIFT))
#define RCC_CICR_LSE_CSSC_YES		(1 << (RCC_CICR_LSE_CSSC_SHIFT))
#define RCC_CICR_CSSC_SHIFT		8
#define RCC_CICR_CSSC_MASK		(1 << (RCC_CICR_LSE_CSSC_SHIFT))
#define RCC_CICR_CSSC_NO		(0 << (RCC_CICR_LSE_CSSC_SHIFT))
#define RCC_CICR_CSSC_YES		(1 << (RCC_CICR_LSE_CSSC_SHIFT))
#define RCC_CICR_PLLSAI1_RDYC_SHIFT	6
#define RCC_CICR_PLLSAI1_RDYC_MASK	(1 << (RCC_CICR_PLLSAI1_RDYC_SHIFT))
#define RCC_CICR_PLLSAI1_RDYC_NO	(0 << (RCC_CICR_PLLSAI1_RDYC_SHIFT))
#define RCC_CICR_PLLSAI1_RDYC_YES	(1 << (RCC_CICR_PLLSAI1_RDYC_SHIFT))
#define RCC_CICR_PLL_RDYC_SHIFT		5
#define RCC_CICR_PLL_RDYC_MASK		(1 << (RCC_CICR_PLL_RDYC_SHIFT))
#define RCC_CICR_PLL_RDYC_NO		(0 << (RCC_CICR_PLL_RDYC_SHIFT))
#define RCC_CICR_PLL_RDYC_YES		(1 << (RCC_CICR_PLL_RDYC_SHIFT))
#define RCC_CICR_HSE_RDYC_SHIFT		4
#define RCC_CICR_HSE_RDYC_MASK		(1 << (RCC_CICR_HSE_RDYC_SHIFT))
#define RCC_CICR_HSE_RDYC_NO		(0 << (RCC_CICR_HSE_RDYC_SHIFT))
#define RCC_CICR_HSE_RDYC_YES		(1 << (RCC_CICR_HSE_RDYC_SHIFT))
#define RCC_CICR_HSI_RDYC_SHIFT		3
#define RCC_CICR_HSI_RDYC_MASK		(1 << (RCC_CICR_HSI_RDYC_SHIFT))
#define RCC_CICR_HSI_RDYC_NO		(0 << (RCC_CICR_HSI_RDYC_SHIFT))
#define RCC_CICR_HSI_RDYC_YES		(1 << (RCC_CICR_HSI_RDYC_SHIFT))
#define RCC_CICR_MSI_RDYC_SHIFT		2
#define RCC_CICR_MSI_RDYC_MASK		(1 << (RCC_CICR_MSI_RDYC_SHIFT))
#define RCC_CICR_MSI_RDYC_NO		(0 << (RCC_CICR_MSI_RDYC_SHIFT))
#define RCC_CICR_MSI_RDYC_YES		(1 << (RCC_CICR_MSI_RDYC_SHIFT))
#define RCC_CICR_LSE_RDYC_SHIFT		1
#define RCC_CICR_LSE_RDYC_MASK		(1 << (RCC_CICR_LSE_RDYC_SHIFT))
#define RCC_CICR_LSE_RDYC_NO		(0 << (RCC_CICR_LSE_RDYC_SHIFT))
#define RCC_CICR_LSE_RDYC_YES		(1 << (RCC_CICR_LSE_RDYC_SHIFT))
#define RCC_CICR_LSI_RDYC_SHIFT		0
#define RCC_CICR_LSI_RDYC_MASK		(1 << (RCC_CICR_LSI_RDYC_SHIFT))
#define RCC_CICR_LSI_RDYC_NO		(0 << (RCC_CICR_LSI_RDYC_SHIFT))
#define RCC_CICR_LSI_RDYC_YES		(1 << (RCC_CICR_LSI_RDYC_SHIFT))
  __IO uint32_t         reserved0x24;   /* 0x24 */
  __IO uint32_t         AHB1RSTR;       /* 0x28 */
#define RCC_APB1RSTR1_CRSRST_SHIFT      24
#define RCC_APB1RSTR1_CRSRST_MASK       (1 << (RCC_APB1RSTR1_CRSRST_SHIFT))
#define RCC_APB1RSTR1_CRSRST_NO         (0 << (RCC_APB1RSTR1_CRSRST_SHIFT))
#define RCC_APB1RSTR1_CRSRST_YES        (1 << (RCC_APB1RSTR1_CRSRST_SHIFT))

  __IO uint32_t         AHB2RSTR;       /* 0x2c */
  __IO uint32_t         AHB3RSTR;       /* 0x30 */
  __IO uint32_t         reserved0x34;   /* 0x34 */
  __IO uint32_t         APB1RSTR1;      /* 0x38 */
  __IO uint32_t         APB1RSTR2;      /* 0x3c */
  __IO uint32_t         APB2RSTR;       /* 0x40 */
#define RCC_APB2RSTR_DFSDM1RSTR_SHIFT	24
#define RCC_APB2RSTR_DFSDM1RSTR_MASK	(1 << (RCC_APB2RSTR_DFSDM1RSTR_SHIFT))
#define RCC_APB2RSTR_DFSDM1RSTR_NO	(0 << (RCC_APB2RSTR_DFSDM1RSTR_SHIFT))
#define RCC_APB2RSTR_DFSDM1RSTR_YES	(1 << (RCC_APB2RSTR_DFSDM1RSTR_SHIFT))
#define RCC_APB2RSTR_SAI1RSTR_SHIFT	21
#define RCC_APB2RSTR_SAI1RSTR_MASK	(1 << (RCC_APB2RSTR_SAI1RSTR_SHIFT))
#define RCC_APB2RSTR_SAI1RSTR_NO	(0 << (RCC_APB2RSTR_SAI1RSTR_SHIFT))
#define RCC_APB2RSTR_SAI1RSTR_YES	(1 << (RCC_APB2RSTR_SAI1RSTR_SHIFT))
#define RCC_APB2RSTR_TIM16RSTR_SHIFT	17
#define RCC_APB2RSTR_TIM16RSTR_MASK	(1 << (RCC_APB2RSTR_TIM16RSTR_SHIFT))
#define RCC_APB2RSTR_TIM16RSTR_NO	(0 << (RCC_APB2RSTR_TIM16RSTR_SHIFT))
#define RCC_APB2RSTR_TIM16RSTR_YES	(1 << (RCC_APB2RSTR_TIM16RSTR_SHIFT))
#define RCC_APB2RSTR_TIM15RSTR_SHIFT	16
#define RCC_APB2RSTR_TIM15RSTR_MASK	(1 << (RCC_APB2RSTR_TIM15RSTR_SHIFT))
#define RCC_APB2RSTR_TIM15RSTR_NO	(0 << (RCC_APB2RSTR_TIM15RSTR_SHIFT))
#define RCC_APB2RSTR_TIM15RSTR_YES	(1 << (RCC_APB2RSTR_TIM15RSTR_SHIFT))
#define RCC_APB2RSTR_USART1RSTR_SHIFT	14
#define RCC_APB2RSTR_USART1RSTR_MASK	(1 << (RCC_APB2RSTR_USART1RSTR_SHIFT))
#define RCC_APB2RSTR_USART1RSTR_NO	(0 << (RCC_APB2RSTR_USART1RSTR_SHIFT))
#define RCC_APB2RSTR_USART1RSTR_YES	(1 << (RCC_APB2RSTR_USART1RSTR_SHIFT))
#define RCC_APB2RSTR_SPI1RSTR_SHIFT	12
#define RCC_APB2RSTR_SPI1RSTR_MASK	(1 << (RCC_APB2RSTR_SPI1RSTR_SHIFT))
#define RCC_APB2RSTR_SPI1RSTR_NO	(0 << (RCC_APB2RSTR_SPI1RSTR_SHIFT))
#define RCC_APB2RSTR_SPI1RSTR_YES	(1 << (RCC_APB2RSTR_SPI1RSTR_SHIFT))
#define RCC_APB2RSTR_TIM1RSTR_SHIFT	11
#define RCC_APB2RSTR_TIM1RSTR_MASK	(1 << (RCC_APB2RSTR_TIM1RSTR_SHIFT))
#define RCC_APB2RSTR_TIM1RSTR_NO	(0 << (RCC_APB2RSTR_TIM1RSTR_SHIFT))
#define RCC_APB2RSTR_TIM1RSTR_YES	(1 << (RCC_APB2RSTR_TIM1RSTR_SHIFT))
#define RCC_APB2RSTR_SDMMC1RSTR_SHIFT	10
#define RCC_APB2RSTR_SDMMC1RSTR_MASK	(1 << (RCC_APB2RSTR_SDMMC1RSTR_SHIFT))
#define RCC_APB2RSTR_SDMMC1RSTR_NO	(0 << (RCC_APB2RSTR_SDMMC1RSTR_SHIFT))
#define RCC_APB2RSTR_SDMMC1RSTR_YES	(1 << (RCC_APB2RSTR_SDMMC1RSTR_SHIFT))
#define RCC_APB2RSTR_FWRSTR_SHIFT	7
#define RCC_APB2RSTR_FWRSTR_MASK	(1 << (RCC_APB2RSTR_FWRSTR_SHIFT))
#define RCC_APB2RSTR_FWRSTR_NO		(0 << (RCC_APB2RSTR_FWRSTR_SHIFT))
#define RCC_APB2RSTR_FWRSTR_YES		(1 << (RCC_APB2RSTR_FWRSTR_SHIFT))
#define RCC_APB2RSTR_SYSCFGRSTR_SHIFT	0
#define RCC_APB2RSTR_SYSCFGRSTR_MASK	(1 << (RCC_APB2RSTR_SYSCFGRSTR_SHIFT))
#define RCC_APB2RSTR_SYSCFGRSTR_NO	(0 << (RCC_APB2RSTR_SYSCFGRSTR_SHIFT))
#define RCC_APB2RSTR_SYSCFGRSTR_YES	(1 << (RCC_APB2RSTR_SYSCFGRSTR_SHIFT))

  __IO uint32_t         reserved0x44;   /* 0x44 */
  __IO uint32_t         AHB1ENR;        /* 0x48 */
#define RCC_AHB1ENR_TSCEN_SHIFT		16
#define RCC_AHB1ENR_TSCEN_MASK		(1 << (RCC_AHB1ENR_TSCEN_SHIFT))
#define RCC_AHB1ENR_TSCEN_NO		(0 << (RCC_AHB1ENR_TSCEN_SHIFT))
#define RCC_AHB1ENR_TSCEN_YES		(1 << (RCC_AHB1ENR_TSCEN_SHIFT))
#define RCC_AHB1ENR_CRCEN_SHIFT		12
#define RCC_AHB1ENR_CRCEN_MASK		(1 << (RCC_AHB1ENR_CRCEN_SHIFT))
#define RCC_AHB1ENR_CRCEN_NO		(0 << (RCC_AHB1ENR_CRCEN_SHIFT))
#define RCC_AHB1ENR_CRCEN_YES		(1 << (RCC_AHB1ENR_CRCEN_SHIFT))
#define RCC_AHB1ENR_FLASHEN_SHIFT	8
#define RCC_AHB1ENR_FLASHEN_MASK	(1 << (RCC_AHB1ENR_FLASHEN_SHIFT))
#define RCC_AHB1ENR_FLASHEN_NO		(0 << (RCC_AHB1ENR_FLASHEN_SHIFT))
#define RCC_AHB1ENR_FLASHEN_YES		(1 << (RCC_AHB1ENR_FLASHEN_SHIFT))
#define RCC_AHB1ENR_DMA2EN_SHIFT	1
#define RCC_AHB1ENR_DMA2EN_MASK		(1 << (RCC_AHB1ENR_DMA2EN_SHIFT))
#define RCC_AHB1ENR_DMA2EN_NO		(0 << (RCC_AHB1ENR_DMA2EN_SHIFT))
#define RCC_AHB1ENR_DMA2EN_YES		(1 << (RCC_AHB1ENR_DMA2EN_SHIFT))
#define RCC_AHB1ENR_DMA1EN_SHIFT	0
#define RCC_AHB1ENR_DMA1EN_MASK		(1 << (RCC_AHB1ENR_DMA1EN_SHIFT))
#define RCC_AHB1ENR_DMA1EN_NO		(0 << (RCC_AHB1ENR_DMA1EN_SHIFT))
#define RCC_AHB1ENR_DMA1EN_YES		(1 << (RCC_AHB1ENR_DMA1EN_SHIFT))

  __IO uint32_t         AHB2ENR;        /* 0x4c */
#define RCC_AHB2ENR_GPIOAEN_SHIFT       0
#define RCC_AHB2ENR_GPIOAEN_MASK        (1 << (RCC_AHB2ENR_GPIOAEN_SHIFT))
#define RCC_AHB2ENR_GPIOAEN_NO          (0 << (RCC_AHB2ENR_GPIOAEN_SHIFT))
#define RCC_AHB2ENR_GPIOAEN_YES         (1 << (RCC_AHB2ENR_GPIOAEN_SHIFT))
#define RCC_AHB2ENR_GPIOBEN_SHIFT       1
#define RCC_AHB2ENR_GPIOBEN_MASK        (1 << (RCC_AHB2ENR_GPIOBEN_SHIFT))
#define RCC_AHB2ENR_GPIOBEN_NO          (0 << (RCC_AHB2ENR_GPIOBEN_SHIFT))
#define RCC_AHB2ENR_GPIOBEN_YES         (1 << (RCC_AHB2ENR_GPIOBEN_SHIFT))
#define RCC_AHB2ENR_GPIOCEN_SHIFT       2
#define RCC_AHB2ENR_GPIOCEN_MASK        (1 << (RCC_AHB2ENR_GPIOCEN_SHIFT))
#define RCC_AHB2ENR_GPIOCEN_NO          (0 << (RCC_AHB2ENR_GPIOCEN_SHIFT))
#define RCC_AHB2ENR_GPIOCEN_YES         (1 << (RCC_AHB2ENR_GPIOCEN_SHIFT))
#define RCC_AHB2ENR_GPIODEN_SHIFT       3
#define RCC_AHB2ENR_GPIODEN_MASK        (1 << (RCC_AHB2ENR_GPIODEN_SHIFT))
#define RCC_AHB2ENR_GPIODEN_NO          (0 << (RCC_AHB2ENR_GPIODEN_SHIFT))
#define RCC_AHB2ENR_GPIODEN_YES         (1 << (RCC_AHB2ENR_GPIODEN_SHIFT))
#define RCC_AHB2ENR_GPIOEEN_SHIFT       4
#define RCC_AHB2ENR_GPIOEEN_MASK        (1 << (RCC_AHB2ENR_GPIOEEN_SHIFT))
#define RCC_AHB2ENR_GPIOEEN_NO          (0 << (RCC_AHB2ENR_GPIOEEN_SHIFT))
#define RCC_AHB2ENR_GPIOEEN_YES         (1 << (RCC_AHB2ENR_GPIOEEN_SHIFT))
#define RCC_AHB2ENR_GPIOHEN_SHIFT       7
#define RCC_AHB2ENR_GPIOHEN_MASK        (1 << (RCC_AHB2ENR_GPIOHEN_SHIFT))
#define RCC_AHB2ENR_GPIOHEN_NO          (0 << (RCC_AHB2ENR_GPIOHEN_SHIFT))
#define RCC_AHB2ENR_GPIOHEN_YES         (1 << (RCC_AHB2ENR_GPIOHEN_SHIFT))

#define RCC_GPIOAEN_YES                 (RCC_AHB2ENR_GPIOAEN_YES)
#define RCC_GPIOBEN_YES                 (RCC_AHB2ENR_GPIOBEN_YES)
#define RCC_GPIOCEN_YES                 (RCC_AHB2ENR_GPIOCEN_YES)
#define RCC_GPIODEN_YES                 (RCC_AHB2ENR_GPIODEN_YES)
#define RCC_GPIOEEN_YES                 (RCC_AHB2ENR_GPIOEEN_YES)
#define RCC_GPIOHEN_YES                 (RCC_AHB2ENR_GPIOHEN_YES)

#define RCC_AHB2ENR_ADCEN_SHIFT         13
#define RCC_AHB2ENR_ADCEN_MASK          (1 << (RCC_AHB2ENR_ADCEN_SHIFT))
#define RCC_AHB2ENR_ADCEN_NO            (0 << (RCC_AHB2ENR_ADCEN_SHIFT))
#define RCC_AHB2ENR_ADCEN_YES           (1 << (RCC_AHB2ENR_ADCEN_SHIFT))
#define RCC_AHB2ENR_AESEN_SHIFT         16
#define RCC_AHB2ENR_AESEN_MASK          (1 << (RCC_AHB2ENR_AESEN_SHIFT))
#define RCC_AHB2ENR_AESEN_NO            (0 << (RCC_AHB2ENR_AESEN_SHIFT))
#define RCC_AHB2ENR_AESEN_YES           (1 << (RCC_AHB2ENR_AESEN_SHIFT))
#define RCC_AHB2ENR_RNGEN_SHIFT         17
#define RCC_AHB2ENR_RNGEN_MASK          (1 << (RCC_AHB2ENR_RNGEN_SHIFT))
#define RCC_AHB2ENR_RNGEN_NO            (0 << (RCC_AHB2ENR_RNGEN_SHIFT))
#define RCC_AHB2ENR_RNGEN_YES           (1 << (RCC_AHB2ENR_RNGEN_SHIFT))

  __IO uint32_t         AHB3ENR;        /* 0x50 */
#define RCC_AHB3ENR_QSPIEN_SHIFT        8
#define RCC_AHB3ENR_QSPIEN_MASK         (1 << (RCC_AHB3ENR_QSPIEN_SHIFT))
#define RCC_AHB3ENR_QSPIEN_NO           (0 << (RCC_AHB3ENR_QSPIEN_SHIFT))
#define RCC_AHB3ENR_QSPIEN_YES          (1 << (RCC_AHB3ENR_QSPIEN_SHIFT))

  __IO uint32_t         reserved0x54;   /* 0x54 */
  __IO uint32_t         APB1ENR1;       /* 0x58 */
#define RCC_APB1ENR1_LPTIM1EN_SHIFT	31
#define RCC_APB1ENR1_LPTIM1EN_MASK	(1 << (RCC_APB1ENR1_LPTIM1EN_SHIFT))
#define RCC_APB1ENR1_LPTIM1EN_NO	(0 << (RCC_APB1ENR1_LPTIM1EN_SHIFT))
#define RCC_APB1ENR1_LPTIM1EN_YES	(1 << (RCC_APB1ENR1_LPTIM1EN_SHIFT))
#define RCC_APB1ENR1_OPAMPEN_SHIFT	30
#define RCC_APB1ENR1_OPAMPEN_MASK	(1 << (RCC_APB1ENR1_OPAMPEN_SHIFT))
#define RCC_APB1ENR1_OPAMPEN_NO		(0 << (RCC_APB1ENR1_OPAMPEN_SHIFT))
#define RCC_APB1ENR1_OPAMPEN_YES	(1 << (RCC_APB1ENR1_OPAMPEN_SHIFT))
#define RCC_APB1ENR1_DAC1EN_SHIFT	29
#define RCC_APB1ENR1_DAC1EN_MASK	(1 << (RCC_APB1ENR1_DAC1EN_SHIFT))
#define RCC_APB1ENR1_DAC1EN_NO		(0 << (RCC_APB1ENR1_DAC1EN_SHIFT))
#define RCC_APB1ENR1_DAC1EN_YES		(1 << (RCC_APB1ENR1_DAC1EN_SHIFT))
#define RCC_APB1ENR1_PWREN_SHIFT	28
#define RCC_APB1ENR1_PWREN_MASK		(1 << (RCC_APB1ENR1_PWREN_SHIFT))
#define RCC_APB1ENR1_PWREN_NO		(0 << (RCC_APB1ENR1_PWREN_SHIFT))
#define RCC_APB1ENR1_PWREN_YES		(1 << (RCC_APB1ENR1_PWREN_SHIFT))
#define RCC_APB1ENR1_USBFSEN_SHIFT	26
#define RCC_APB1ENR1_USBFSEN_MASK	(1 << (RCC_APB1ENR1_USBFSEN_SHIFT))
#define RCC_APB1ENR1_USBFSEN_NO		(0 << (RCC_APB1ENR1_USBFSEN_SHIFT))
#define RCC_APB1ENR1_USBFSEN_YES	(1 << (RCC_APB1ENR1_USBFSEN_SHIFT))
#define RCC_APB1ENR1_CAN1EN_SHIFT	25
#define RCC_APB1ENR1_CAN1EN_MASK	(1 << (RCC_APB1ENR1_CAN1EN_SHIFT))
#define RCC_APB1ENR1_CAN1EN_NO		(0 << (RCC_APB1ENR1_CAN1EN_SHIFT))
#define RCC_APB1ENR1_CAN1EN_YES		(1 << (RCC_APB1ENR1_CAN1EN_SHIFT))
#define RCC_APB1ENR1_CRSEN_SHIFT	24
#define RCC_APB1ENR1_CRSEN_MASK		(1 << (RCC_APB1ENR1_CRSEN_SHIFT))
#define RCC_APB1ENR1_CRSEN_NO		(0 << (RCC_APB1ENR1_CRSEN_SHIFT))
#define RCC_APB1ENR1_CRSEN_YES		(1 << (RCC_APB1ENR1_CRSEN_SHIFT))
#define RCC_APB1ENR1_I2C3EN_SHIFT	23
#define RCC_APB1ENR1_I2C3EN_MASK	(1 << (RCC_APB1ENR1_I2C3EN_SHIFT))
#define RCC_APB1ENR1_I2C3EN_NO		(0 << (RCC_APB1ENR1_I2C3EN_SHIFT))
#define RCC_APB1ENR1_I2C3EN_YES		(1 << (RCC_APB1ENR1_I2C3EN_SHIFT))
#define RCC_APB1ENR1_I2C2EN_SHIFT	22
#define RCC_APB1ENR1_I2C2EN_MASK	(1 << (RCC_APB1ENR1_I2C2EN_SHIFT))
#define RCC_APB1ENR1_I2C2EN_NO		(0 << (RCC_APB1ENR1_I2C2EN_SHIFT))
#define RCC_APB1ENR1_I2C2EN_YES		(1 << (RCC_APB1ENR1_I2C2EN_SHIFT))
#define RCC_APB1ENR1_I2C1EN_SHIFT	21
#define RCC_APB1ENR1_I2C1EN_MASK	(1 << (RCC_APB1ENR1_I2C1EN_SHIFT))
#define RCC_APB1ENR1_I2C1EN_NO		(0 << (RCC_APB1ENR1_I2C1EN_SHIFT))
#define RCC_APB1ENR1_I2C1EN_YES		(1 << (RCC_APB1ENR1_I2C1EN_SHIFT))
#define RCC_APB1ENR1_UART4EN_SHIFT	19
#define RCC_APB1ENR1_UART4EN_MASK	(1 << (RCC_APB1ENR1_UART4EN_SHIFT))
#define RCC_APB1ENR1_UART4EN_NO		(0 << (RCC_APB1ENR1_UART4EN_SHIFT))
#define RCC_APB1ENR1_UART4EN_YES	(1 << (RCC_APB1ENR1_UART4EN_SHIFT))
#define RCC_APB1ENR1_USART3EN_SHIFT	18
#define RCC_APB1ENR1_USART3EN_MASK	(1 << (RCC_APB1ENR1_USART3EN_SHIFT))
#define RCC_APB1ENR1_USART3EN_NO	(0 << (RCC_APB1ENR1_USART3EN_SHIFT))
#define RCC_APB1ENR1_USART3EN_YES	(1 << (RCC_APB1ENR1_USART3EN_SHIFT))
#define RCC_APB1ENR1_USART2EN_SHIFT	17
#define RCC_APB1ENR1_USART2EN_MASK	(1 << (RCC_APB1ENR1_USART2EN_SHIFT))
#define RCC_APB1ENR1_USART2EN_NO	(0 << (RCC_APB1ENR1_USART2EN_SHIFT))
#define RCC_APB1ENR1_USART2EN_YES	(1 << (RCC_APB1ENR1_USART2EN_SHIFT))
#define RCC_APB1ENR1_SPI3EN_SHIFT	15
#define RCC_APB1ENR1_SPI3EN_MASK	(1 << (RCC_APB1ENR1_SPI3EN_SHIFT))
#define RCC_APB1ENR1_SPI3EN_NO		(0 << (RCC_APB1ENR1_SPI3EN_SHIFT))
#define RCC_APB1ENR1_SPI3EN_YES		(1 << (RCC_APB1ENR1_SPI3EN_SHIFT))
#define RCC_APB1ENR1_SPI2EN_SHIFT	14
#define RCC_APB1ENR1_SPI2EN_MASK	(1 << (RCC_APB1ENR1_SPI2EN_SHIFT))
#define RCC_APB1ENR1_SPI2EN_NO		(0 << (RCC_APB1ENR1_SPI2EN_SHIFT))
#define RCC_APB1ENR1_SPI2EN_YES		(1 << (RCC_APB1ENR1_SPI2EN_SHIFT))
#define RCC_APB1ENR1_WWDGEN_SHIFT	11
#define RCC_APB1ENR1_WWDGEN_MASK	(1 << (RCC_APB1ENR1_WWDGEN_SHIFT))
#define RCC_APB1ENR1_WWDGEN_NO		(0 << (RCC_APB1ENR1_WWDGEN_SHIFT))
#define RCC_APB1ENR1_WWDGEN_YES		(1 << (RCC_APB1ENR1_WWDGEN_SHIFT))
#define RCC_APB1ENR1_RTCAPBEN_SHIFT	10
#define RCC_APB1ENR1_RTCAPBEN_MASK	(1 << (RCC_APB1ENR1_RTCAPBEN_SHIFT))
#define RCC_APB1ENR1_RTCAPBEN_NO	(0 << (RCC_APB1ENR1_RTCAPBEN_SHIFT))
#define RCC_APB1ENR1_RTCAPBEN_YES	(1 << (RCC_APB1ENR1_RTCAPBEN_SHIFT))
#define RCC_APB1ENR1_LEDEN_SHIFT	9
#define RCC_APB1ENR1_LEDEN_MASK		(1 << (RCC_APB1ENR1_LEDEN_SHIFT))
#define RCC_APB1ENR1_LEDEN_NO		(0 << (RCC_APB1ENR1_LEDEN_SHIFT))
#define RCC_APB1ENR1_LEDEN_YES		(1 << (RCC_APB1ENR1_LEDEN_SHIFT))
#define RCC_APB1ENR1_TIM7EN_SHIFT	5
#define RCC_APB1ENR1_TIM7EN_MASK	(1 << (RCC_APB1ENR1_TIM7EN_SHIFT))
#define RCC_APB1ENR1_TIM7EN_NO		(0 << (RCC_APB1ENR1_TIM7EN_SHIFT))
#define RCC_APB1ENR1_TIM7EN_YES		(1 << (RCC_APB1ENR1_TIM7EN_SHIFT))
#define RCC_APB1ENR1_TIM6EN_SHIFT	4
#define RCC_APB1ENR1_TIM6EN_MASK	(1 << (RCC_APB1ENR1_TIM6EN_SHIFT))
#define RCC_APB1ENR1_TIM6EN_NO		(0 << (RCC_APB1ENR1_TIM6EN_SHIFT))
#define RCC_APB1ENR1_TIM6EN_YES		(1 << (RCC_APB1ENR1_TIM6EN_SHIFT))
#define RCC_APB1ENR1_TIM3EN_SHIFT	1
#define RCC_APB1ENR1_TIM3EN_MASK	(1 << (RCC_APB1ENR1_TIM3EN_SHIFT))
#define RCC_APB1ENR1_TIM3EN_NO		(0 << (RCC_APB1ENR1_TIM3EN_SHIFT))
#define RCC_APB1ENR1_TIM3EN_YES		(1 << (RCC_APB1ENR1_TIM3EN_SHIFT))
#define RCC_APB1ENR1_TIM2EN_SHIFT	0
#define RCC_APB1ENR1_TIM2EN_MASK	(1 << (RCC_APB1ENR1_TIM2EN_SHIFT))
#define RCC_APB1ENR1_TIM2EN_NO		(0 << (RCC_APB1ENR1_TIM2EN_SHIFT))
#define RCC_APB1ENR1_TIM2EN_YES		(1 << (RCC_APB1ENR1_TIM2EN_SHIFT))

  __IO uint32_t         APB1ENR2;       /* 0x5c */
#define RCC_APB1ENR2_LPTIM2EN_SHIFT	5
#define RCC_APB1ENR2_LPTIM2EN_MASK	(1 << (RCC_APB1ENR2_LPTIM2EN_SHIFT))
#define RCC_APB1ENR2_LPTIM2EN_NO	(0 << (RCC_APB1ENR2_LPTIM2EN_SHIFT))
#define RCC_APB1ENR2_LPTIM2EN_YES	(1 << (RCC_APB1ENR2_LPTIM2EN_SHIFT))
#define RCC_APB1ENR2_SWPMI1EN_SHIFT	2
#define RCC_APB1ENR2_SWPMI1EN_MASK	(1 << (RCC_APB1ENR2_SWPMI1EN_SHIFT))
#define RCC_APB1ENR2_SWPMI1EN_NO	(0 << (RCC_APB1ENR2_SWPMI1EN_SHIFT))
#define RCC_APB1ENR2_SWPMI1EN_YES	(1 << (RCC_APB1ENR2_SWPMI1EN_SHIFT))
#define RCC_APB1ENR2_I2C4EN_SHIFT	1
#define RCC_APB1ENR2_I2C4EN_MASK	(1 << (RCC_APB1ENR2_I2C4EN_SHIFT))
#define RCC_APB1ENR2_I2C4EN_NO		(0 << (RCC_APB1ENR2_I2C4EN_SHIFT))
#define RCC_APB1ENR2_I2C4EN_YES		(1 << (RCC_APB1ENR2_I2C4EN_SHIFT))
#define RCC_APB1ENR2_LPUART1EN_SHIFT	0
#define RCC_APB1ENR2_LPUART1EN_MASK	(1 << (RCC_APB1ENR2_LPUART1EN_SHIFT))
#define RCC_APB1ENR2_LPUART1EN_NO	(0 << (RCC_APB1ENR2_LPUART1EN_SHIFT))
#define RCC_APB1ENR2_LPUART1EN_YES	(1 << (RCC_APB1ENR2_LPUART1EN_SHIFT))

  __IO uint32_t         APB2ENR;        /* 0x60 */
#define RCC_APB2ENR_DFSDM1EN_SHIFT	24
#define RCC_APB2ENR_DFSDM1EN_MASK	(1 << (RCC_APB2ENR_DFSDM1EN_SHIFT))
#define RCC_APB2ENR_DFSDM1EN_NO		(0 << (RCC_APB2ENR_DFSDM1EN_SHIFT))
#define RCC_APB2ENR_DFSDM1EN_YES	(1 << (RCC_APB2ENR_DFSDM1EN_SHIFT))
#define RCC_APB2ENR_SAI1EN_SHIFT	21
#define RCC_APB2ENR_SAI1EN_MASK		(1 << (RCC_APB2ENR_SAI1EN_SHIFT))
#define RCC_APB2ENR_SAI1EN_NO		(0 << (RCC_APB2ENR_SAI1EN_SHIFT))
#define RCC_APB2ENR_SAI1EN_YES		(1 << (RCC_APB2ENR_SAI1EN_SHIFT))
#define RCC_APB2ENR_TIM16EN_SHIFT	17
#define RCC_APB2ENR_TIM16EN_MASK	(1 << (RCC_APB2ENR_TIM16EN_SHIFT))
#define RCC_APB2ENR_TIM16EN_NO		(0 << (RCC_APB2ENR_TIM16EN_SHIFT))
#define RCC_APB2ENR_TIM16EN_YES		(1 << (RCC_APB2ENR_TIM16EN_SHIFT))
#define RCC_APB2ENR_TIM15EN_SHIFT	16
#define RCC_APB2ENR_TIM15EN_MASK	(1 << (RCC_APB2ENR_TIM15EN_SHIFT))
#define RCC_APB2ENR_TIM15EN_NO		(0 << (RCC_APB2ENR_TIM15EN_SHIFT))
#define RCC_APB2ENR_TIM15EN_YES		(1 << (RCC_APB2ENR_TIM15EN_SHIFT))
#define RCC_APB2ENR_USART1EN_SHIFT	14
#define RCC_APB2ENR_USART1EN_MASK	(1 << (RCC_APB2ENR_USART1EN_SHIFT))
#define RCC_APB2ENR_USART1EN_NO		(0 << (RCC_APB2ENR_USART1EN_SHIFT))
#define RCC_APB2ENR_USART1EN_YES	(1 << (RCC_APB2ENR_USART1EN_SHIFT))
#define RCC_APB2ENR_SPI1EN_SHIFT	12
#define RCC_APB2ENR_SPI1EN_MASK		(1 << (RCC_APB2ENR_SPI1EN_SHIFT))
#define RCC_APB2ENR_SPI1EN_NO		(0 << (RCC_APB2ENR_SPI1EN_SHIFT))
#define RCC_APB2ENR_SPI1EN_YES		(1 << (RCC_APB2ENR_SPI1EN_SHIFT))
#define RCC_APB2ENR_TIM1EN_SHIFT	11
#define RCC_APB2ENR_TIM1EN_MASK		(1 << (RCC_APB2ENR_TIM1EN_SHIFT))
#define RCC_APB2ENR_TIM1EN_NO		(0 << (RCC_APB2ENR_TIM1EN_SHIFT))
#define RCC_APB2ENR_TIM1EN_YES		(1 << (RCC_APB2ENR_TIM1EN_SHIFT))
#define RCC_APB2ENR_SDMMC1EN_SHIFT	10
#define RCC_APB2ENR_SDMMC1EN_MASK	(1 << (RCC_APB2ENR_SDMMC1EN_SHIFT))
#define RCC_APB2ENR_SDMMC1EN_NO		(0 << (RCC_APB2ENR_SDMMC1EN_SHIFT))
#define RCC_APB2ENR_SDMMC1EN_YES	(1 << (RCC_APB2ENR_SDMMC1EN_SHIFT))
#define RCC_APB2ENR_FWEN_SHIFT		7
#define RCC_APB2ENR_FWEN_MASK		(1 << (RCC_APB2ENR_FWEN_SHIFT))
#define RCC_APB2ENR_FWEN_NO		(0 << (RCC_APB2ENR_FWEN_SHIFT))
#define RCC_APB2ENR_FWEN_YES		(1 << (RCC_APB2ENR_FWEN_SHIFT))
#define RCC_APB2ENR_SYSCFGEN_SHIFT	0
#define RCC_APB2ENR_SYSCFGEN_MASK	(1 << (RCC_APB2ENR_SYSCFGEN_SHIFT))
#define RCC_APB2ENR_SYSCFGEN_NO		(0 << (RCC_APB2ENR_SYSCFGEN_SHIFT))
#define RCC_APB2ENR_SYSCFGEN_YES	(1 << (RCC_APB2ENR_SYSCFGEN_SHIFT))

  __IO uint32_t         reserved0x64;   /* 0x64 */
  __IO uint32_t         AHB1SMENR;      /* 0x68 */
  __IO uint32_t         AHB2SMENR;      /* 0x6c */
  __IO uint32_t         AHB3SMENR;      /* 0x70 */
  __IO uint32_t         reserved0x74;   /* 0x74 */
  __IO uint32_t         APB1SMENR1;     /* 0x78 */
  __IO uint32_t         APB1SMENR2;     /* 0x7c */
  __IO uint32_t         APB2SMENR;      /* 0x80 */
  __IO uint32_t         reserved0x84;   /* 0x84 */
  __IO uint32_t         CCIPR;          /* 0x88 */
#define RCC_CCIPR_SWPMI1SEL_SHIFT       30
#define RCC_CCIPR_SWPMI1SEL_MASK        (1 << (RCC_CCIPR_SWPMI1SEL_SHIFT))
#define RCC_CCIPR_SWPMI1SEL_PCLK1       (0 << (RCC_CCIPR_SWPMI1SEL_SHIFT))
#define RCC_CCIPR_SWPMI1SEL_HSI16       (1 << (RCC_CCIPR_SWPMI1SEL_SHIFT))
#define RCC_CCIPR_ADCSEL_SHIFT          28
#define RCC_CCIPR_ADCSEL_MASK           (3 << (RCC_CCIPR_ADCSEL_SHIFT))
#define RCC_CCIPR_ADCSEL_NONE           (0 << (RCC_CCIPR_ADCSEL_SHIFT))
#define RCC_CCIPR_ADCSEL_PLLSAI1R       (1 << (RCC_CCIPR_ADCSEL_SHIFT))
#define RCC_CCIPR_ADCSEL_RESERVED2      (2 << (RCC_CCIPR_ADCSEL_SHIFT))
#define RCC_CCIPR_ADCSEL_SYSCLK         (3 << (RCC_CCIPR_ADCSEL_SHIFT))
#define RCC_CCIPR_CLK48SEL_SHIFT        26
#define RCC_CCIPR_CLK48SEL_MASK         (3 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_CLK48SEL_HSI48        (0 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_CLK48SEL_PLLSAIQ      (1 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_CLK48SEL_PLLQ         (2 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_CLK48SEL_MSI          (3 << (RCC_CCIPR_CLK48SEL_SHIFT))
#define RCC_CCIPR_SAI1SEL_SHIFT         22
#define RCC_CCIPR_SAI1SEL_MASK          (3 << (RCC_CCIPR_SAI1SEL_SHIFT))
#define RCC_CCIPR_SAI1SEL_PLLSAI1P      (0 << (RCC_CCIPR_SAI1SEL_SHIFT))
#define RCC_CCIPR_SAI1SEL_RESERVED1     (1 << (RCC_CCIPR_SAI1SEL_SHIFT))
#define RCC_CCIPR_SAI1SEL_PLLP          (2 << (RCC_CCIPR_SAI1SEL_SHIFT))
#define RCC_CCIPR_SAI1SEL_SAI1_EXTCLK   (3 << (RCC_CCIPR_SAI1SEL_SHIFT))
#define RCC_CCIPR_LPTIM2SEL_SHIFT       20
#define RCC_CCIPR_LPTIM2SEL_MASK        (3 << (RCC_CCIPR_LPTIM2SEL_SHIFT))
#define RCC_CCIPR_LPTIM2SEL_PCLK        (0 << (RCC_CCIPR_LPTIM2SEL_SHIFT))
#define RCC_CCIPR_LPTIM2SEL_LSI         (1 << (RCC_CCIPR_LPTIM2SEL_SHIFT))
#define RCC_CCIPR_LPTIM2SEL_HSI16       (2 << (RCC_CCIPR_LPTIM2SEL_SHIFT))
#define RCC_CCIPR_LPTIM2SEL_LSE         (3 << (RCC_CCIPR_LPTIM2SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_SHIFT       18
#define RCC_CCIPR_LPTIM1SEL_MASK        (3 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_PCLK        (0 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_LSI         (1 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_HSI16       (2 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_LPTIM1SEL_LSE         (3 << (RCC_CCIPR_LPTIM1SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_SHIFT         16
#define RCC_CCIPR_I2C3SEL_MASK          (3 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_PCLK          (0 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_SYSCLK        (1 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_HSI16         (2 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C3SEL_RESERVED3     (3 << (RCC_CCIPR_I2C3SEL_SHIFT))
#define RCC_CCIPR_I2C2SEL_SHIFT         14
#define RCC_CCIPR_I2C2SEL_MASK          (3 << (RCC_CCIPR_I2C2SEL_SHIFT))
#define RCC_CCIPR_I2C2SEL_PCLK          (0 << (RCC_CCIPR_I2C2SEL_SHIFT))
#define RCC_CCIPR_I2C2SEL_SYSCLK        (1 << (RCC_CCIPR_I2C2SEL_SHIFT))
#define RCC_CCIPR_I2C2SEL_HSI16         (2 << (RCC_CCIPR_I2C2SEL_SHIFT))
#define RCC_CCIPR_I2C2SEL_RESERVED3     (3 << (RCC_CCIPR_I2C2SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_SHIFT         12
#define RCC_CCIPR_I2C1SEL_MASK          (3 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_PCLK          (0 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_SYSCLK        (1 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_HSI16         (2 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_I2C1SEL_RESERVED3     (3 << (RCC_CCIPR_I2C1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_SHIFT      10
#define RCC_CCIPR_LPUART1SEL_MASK       (3 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_PCLK       (0 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_SYSCLK     (1 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_HSI16      (2 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_LPUART1SEL_LSE        (3 << (RCC_CCIPR_LPUART1SEL_SHIFT))
#define RCC_CCIPR_UART4SEL_SHIFT        6
#define RCC_CCIPR_UART4SEL_MASK         (3 << (RCC_CCIPR_UART4SEL_SHIFT))
#define RCC_CCIPR_UART4SEL_PCLK         (0 << (RCC_CCIPR_UART4SEL_SHIFT))
#define RCC_CCIPR_UART4SEL_SYSCLK       (1 << (RCC_CCIPR_UART4SEL_SHIFT))
#define RCC_CCIPR_UART4SEL_HSI16        (2 << (RCC_CCIPR_UART4SEL_SHIFT))
#define RCC_CCIPR_UART4SEL_LSE          (3 << (RCC_CCIPR_UART4SEL_SHIFT))
#define RCC_CCIPR_USART3SEL_SHIFT       4
#define RCC_CCIPR_USART3SEL_MASK        (3 << (RCC_CCIPR_USART3SEL_SHIFT))
#define RCC_CCIPR_USART3SEL_PCLK	(0 << (RCC_CCIPR_USART3SEL_SHIFT))
#define RCC_CCIPR_USART3SEL_SYSCLK	(1 << (RCC_CCIPR_USART3SEL_SHIFT))
#define RCC_CCIPR_USART3SEL_HSI16	(2 << (RCC_CCIPR_USART3SEL_SHIFT))
#define RCC_CCIPR_USART3SEL_LSE		(3 << (RCC_CCIPR_USART3SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_SHIFT	2
#define RCC_CCIPR_USART2SEL_MASK	(3 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_PCLK	(0 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_SYSCLK      (1 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_HSI16       (2 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART2SEL_LSE         (3 << (RCC_CCIPR_USART2SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_SHIFT       0
#define RCC_CCIPR_USART1SEL_MASK        (3 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_PCLK        (0 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_SYSCLK      (1 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_HSI16       (2 << (RCC_CCIPR_USART1SEL_SHIFT))
#define RCC_CCIPR_USART1SEL_LSE         (3 << (RCC_CCIPR_USART1SEL_SHIFT))
  
  __IO uint32_t         reserved0x8c;   /* 0x8c */
  __IO uint32_t         BDCR;           /* 0x90 */
#define RCC_BDCR_LSCOSEL_SHIFT		25
#define RCC_BDCR_LSCOSEL_MASK		(1 << (RCC_BDCR_LSCOSEL_SHIFT))
#define RCC_BDCR_LSCOSEL_NO		(0 << (RCC_BDCR_LSCOSEL_SHIFT))
#define RCC_BDCR_LSCOSEL_YES		(1 << (RCC_BDCR_LSCOSEL_SHIFT))
#define RCC_BDCR_LSCOEN_SHIFT		24
#define RCC_BDCR_LSCOEN_MASK		(1 << (RCC_BDCR_LSCOEN_SHIFT))
#define RCC_BDCR_LSCOEN_NO		(0 << (RCC_BDCR_LSCOEN_SHIFT))
#define RCC_BDCR_LSCOEN_YES		(1 << (RCC_BDCR_LSCOEN_SHIFT))
#define RCC_BDCR_BDRST_SHIFT		16
#define RCC_BDCR_BDRST_MASK		(1 << (RCC_BDCR_BDRST_SHIFT))
#define RCC_BDCR_BDRST_NO		(0 << (RCC_BDCR_BDRST_SHIFT))
#define RCC_BDCR_BDRST_YES		(1 << (RCC_BDCR_BDRST_SHIFT))
#define RCC_BDCR_RTCEN_SHIFT		15
#define RCC_BDCR_RTCEN_MASK		(1 << (RCC_BDCR_RTCEN_SHIFT))
#define RCC_BDCR_RTCEN_NO		(0 << (RCC_BDCR_RTCEN_SHIFT))
#define RCC_BDCR_RTCEN_YES		(1 << (RCC_BDCR_RTCEN_SHIFT))
#define RCC_BDCR_RTCSELSEL_SHIFT        8
#define RCC_BDCR_RTCSELSEL_MASK         (3 << (RCC_BDCR_RTCSELSEL_SHIFT))
#define RCC_BDCR_RTCSELSEL_NONE RCC_BDCR        (0 << (RCC_BDCR_RTCSELSEL_SHIFT))
#define RCC_BDCR_RTCSELSEL_LSE	        (1 << (RCC_BDCR_RTCSELSEL_SHIFT))
#define RCC_BDCR_RTCSELSEL_LSI	        (2 << (RCC_BDCR_RTCSELSEL_SHIFT))
#define RCC_BDCR_RTCSELSEL_HSE	        (3 << (RCC_BDCR_RTCSELSEL_SHIFT))
#define RCC_BDCR_LSECSSD_SHIFT	        6
#define RCC_BDCR_LSECSSD_MASK	        (1 << (RCC_BDCR_LSECSSD_SHIFT))
#define RCC_BDCR_LSECSSD_NO	        (0 << (RCC_BDCR_LSECSSD_SHIFT))
#define RCC_BDCR_LSECSSD_YES	        (1 << (RCC_BDCR_LSECSSD_SHIFT))
#define RCC_BDCR_LSECSSON_SHIFT         5
#define RCC_BDCR_LSECSSON_MASK	        (1 << (RCC_BDCR_LSECSSON_SHIFT))
#define RCC_BDCR_LSECSSON_NO	        (0 << (RCC_BDCR_LSECSSON_SHIFT))
#define RCC_BDCR_LSECSSON_YES           (1 << (RCC_BDCR_LSECSSON_SHIFT))
#define RCC_BDCR_LSEDRVSEL_SHIFT	3
#define RCC_BDCR_LSEDRVSEL_MASK		(3 << (RCC_BDCR_LSEDRVSEL_SHIFT))
#define RCC_BDCR_LSEDRVSEL_LOWERCAP	(0 << (RCC_BDCR_LSEDRVSEL_SHIFT))
#define RCC_BDCR_LSEDRVSEL_MEDLOWCAP	(1 << (RCC_BDCR_LSEDRVSEL_SHIFT))
#define RCC_BDCR_LSEDRVSEL_MEDHIGHCAP	(2 << (RCC_BDCR_LSEDRVSEL_SHIFT))
#define RCC_BDCR_LSEDRVSEL_HIGHERCAP	(3 << (RCC_BDCR_LSEDRVSEL_SHIFT))
#define RCC_BDCR_LSEBYP_SHIFT		2
#define RCC_BDCR_LSEBYP_MASK		(1 << (RCC_BDCR_LSEBYP_SHIFT))
#define RCC_BDCR_LSEBYP_NO		(0 << (RCC_BDCR_LSEBYP_SHIFT))
#define RCC_BDCR_LSEBYP_YES		(1 << (RCC_BDCR_LSEBYP_SHIFT))
#define RCC_BDCR_LSERDY_SHIFT		1
#define RCC_BDCR_LSERDY_MASK		(1 << (RCC_BDCR_LSERDY_SHIFT))
#define RCC_BDCR_LSERDY_NO		(0 << (RCC_BDCR_LSERDY_SHIFT))
#define RCC_BDCR_LSERDY_YES		(1 << (RCC_BDCR_EN_SHIFT))
#define RCC_BDCR_LSEON_SHIFT		0
#define RCC_BDCR_LSEON_MASK		(1 << (RCC_BDCR_LSEON_SHIFT))
#define RCC_BDCR_LSEON_NO		(0 << (RCC_BDCR_LSEON_SHIFT))
#define RCC_BDCR_LSEON_YES		(1 << (RCC_BDCR_LSEON_SHIFT))

  __IO uint32_t                 CSR;    /* 0x94 */
#define RCC_CSR_LPWRRSTF_SHIFT		31
#define RCC_CSR_LPWRRSTF_MASK		(1 << (RCC_CSR_LPWRRSTF_SHIFT))
#define RCC_CSR_LPWRRSTF_NO		(0 << (RCC_CSR_LPWRRSTF_SHIFT))
#define RCC_CSR_LPWRRSTF_YES		(1 << (RCC_CSR_LPWRRSTF_SHIFT))
#define RCC_CSR_WWDGRSTF_SHIFT		30
#define RCC_CSR_WWDGRSTF_MASK		(1 << (RCC_CSR_WWDGRSTF_SHIFT))
#define RCC_CSR_WWDGRSTF_NO		(0 << (RCC_CSR_WWDGRSTF_SHIFT))
#define RCC_CSR_WWDGRSTF_YES		(1 << (RCC_CSR_WWDGRSTF_SHIFT))
#define RCC_CSR_IWWGRSTF_SHIFT		29
#define RCC_CSR_IWWGRSTF_MASK		(1 << (RCC_CSR_IWWGRSTF_SHIFT))
#define RCC_CSR_IWWGRSTF_NO		(0 << (RCC_CSR_IWWGRSTF_SHIFT))
#define RCC_CSR_IWWGRSTF_YES		(1 << (RCC_CSR_IWWGRSTF_SHIFT))
#define RCC_CSR_SFTRSTF_SHIFT		28
#define RCC_CSR_SFTRSTF_MASK		(1 << (RCC_CSR_SFTRSTF_SHIFT))
#define RCC_CSR_SFTRSTF_NO		(0 << (RCC_CSR_SFTRSTF_SHIFT))
#define RCC_CSR_SFTRSTF_YES		(1 << (RCC_CSR_SFTRSTF_SHIFT))
#define RCC_CSR_BORRSTF_SHIFT		27
#define RCC_CSR_BORRSTF_MASK		(1 << (RCC_CSR_BORRSTF_SHIFT))
#define RCC_CSR_BORRSTF_NO		(0 << (RCC_CSR_BORRSTF_SHIFT))
#define RCC_CSR_BORRSTF_YES		(1 << (RCC_CSR_BORRSTF_SHIFT))
#define RCC_CSR_PINRSTF_SHIFT		26
#define RCC_CSR_PINRSTF_MASK		(1 << (RCC_CSR_PINRSTF_SHIFT))
#define RCC_CSR_PINRSTF_NO		(0 << (RCC_CSR_PINRSTF_SHIFT))
#define RCC_CSR_PINRSTF_YES		(1 << (RCC_CSR_PINRSTF_SHIFT))
#define RCC_CSR_OBLRSTF_SHIFT		25
#define RCC_CSR_OBLRSTF_MASK		(1 << (RCC_CSR_OBLRSTF_SHIFT))
#define RCC_CSR_OBLRSTF_NO		(0 << (RCC_CSR_OBLRSTF_SHIFT))
#define RCC_CSR_OBLRSTF_YES		(1 << (RCC_CSR_OBLRSTF_SHIFT))
#define RCC_CSR_FWRSTF_SHIFT		24
#define RCC_CSR_FWRSTF_MASK		(1 << (RCC_CSR_FWRSTF_SHIFT))
#define RCC_CSR_FWRSTF_NO		(0 << (RCC_CSR_FWRSTF_SHIFT))
#define RCC_CSR_FWRSTF_YES		(1 << (RCC_CSR_FWRSTF_SHIFT))
#define RCC_CSR_RMVF_SHIFT		23
#define RCC_CSR_RMVF_MASK		(1 << (RCC_CSR_RMVF_SHIFT))
#define RCC_CSR_RMVF_NO		        (0 << (RCC_CSR_RMVF_SHIFT))
#define RCC_CSR_RMVF_YES		(1 << (RCC_CSR_RMVF_SHIFT))
#define RCC_CSR_MSISRANGE_SHIFT         8
#define RCC_CSR_MSISRANGE_MASK		(0xf << (RCC_CSR_MSISRANGE_SHIFT))
#define RCC_CSR_MSISRANGE_1MHZ		(4 << (RCC_CSR_MSISRANGE_SHIFT))
#define RCC_CSR_MSISRANGE_2MHZ		(5 << (RCC_CSR_MSISRANGE_SHIFT))
#define RCC_CSR_MSISRANGE_4MHZ		(6 << (RCC_CSR_MSISRANGE_SHIFT))
#define RCC_CSR_MSISRANGE_8MHZ		(7 << (RCC_CSR_MSISRANGE_SHIFT))
#define RCC_CSR_LSIRDY_SHIFT		1
#define RCC_CSR_LSIRDY_MASK		(1 << (RCC_CSR_LSIRDY_SHIFT))
#define RCC_CSR_LSIRDY_NO		(0 << (RCC_CSR_LSIRDY_SHIFT))
#define RCC_CSR_LSIRDY_YES		(1 << (RCC_CSR_LSIRDY_SHIFT))
#define RCC_CSR_LSION_SHIFT		0
#define RCC_CSR_LSION_MASK		(1 << (RCC_CSR_LSION_SHIFT))
#define RCC_CSR_LSION_NO		(0 << (RCC_CSR_LSION_SHIFT))
#define RCC_CSR_LSION_YES		(1 << (RCC_CSR_LSION_SHIFT))

  __IO uint32_t         CRRCR;          /* 0x98 */
#define RCC_CRRCR_HSI48CAL_SHIFT        8
#define RCC_CRRCR_HSI48CAL_MASK         (0xff << (RCC_CRRCR_HSI48CAL_SHIFT))
#define RCC_CRRCR_HSI48RDY_SHIFT        1
#define RCC_CRRCR_HSI48RDY_MASK         (1 << (RCC_CRRCR_HSI48RDY_SHIFT))
#define RCC_CRRCR_HSI48RDY_NO           (0 << (RCC_CRRCR_HSI48RDY_SHIFT))
#define RCC_CRRCR_HSI48RDY_YES          (1 << (RCC_CRRCR_HSI48RDY_SHIFT))
#define RCC_CRRCR_HSI48ON_SHIFT         0
#define RCC_CRRCR_HSI48ON_MASK          (1 << (RCC_CRRCR_HSI48ON_SHIFT))
#define RCC_CRRCR_HSI48ON_NO            (0 << (RCC_CRRCR_HSI48ON_SHIFT))
#define RCC_CRRCR_HSI48ON_YES           (1 << (RCC_CRRCR_HSI48ON_SHIFT))

  __IO uint32_t         CCIPR2;         /* 0x9c */
#define RCC_CCIPR2_I2C4SEL_SHIFT        0
#define RCC_CCIPR2_I2C4SEL_MASK         (3 << (RCC_CCIPR2_I2C4SEL_SHIFT))
#define RCC_CCIPR2_I2C4SEL_PCLK         (0 << (RCC_CCIPR2_I2C4SEL_SHIFT))
#define RCC_CCIPR2_I2C4SEL_SYSCLK       (1 << (RCC_CCIPR2_I2C4SEL_SHIFT))
#define RCC_CCIPR2_I2C4SEL_HSI16        (2 << (RCC_CCIPR2_I2C4SEL_SHIFT))
#define RCC_CCIPR2_I2C4SEL_RESERVED3    (3 << (RCC_CCIPR2_I2C4SEL_SHIFT))
} stm32Dev_RCC;

#endif
